// AUTO-GENERATED from Summit Exteriors LLC Products & Services export (2026-05-29).
// Imported into material_prices on startup. Unit cost = the 'Cost' column.
// Tuple order: [material_key, category, description, unit, unit_cost, sku]
export const SUMMIT_MATERIAL_PRICES: Array<[string, string, string, string, number, string]> = [
  ['SUMMIT_12_1_5_8_FASTENERS_TPO_M', 'Summit Exteriors', '#12 1-5/8 Fasteners - TPO (M)', 'EA', 83.5, ''],
  ['SUMMIT_12_10_FASTENERS_M', 'Summit Exteriors', '#12 10 Fasteners (M)', 'EA', 550.0, ''],
  ['SUMMIT_12_2_1_4_FASTENERS_TPO_M', 'Summit Exteriors', '#12 2-1/4 Fasteners - TPO (M)', 'EA', 99.61, ''],
  ['SUMMIT_12_3_FASTENERS_TPO_M', 'Summit Exteriors', '#12 3 Fasteners - TPO (M)', 'EA', 133.96, ''],
  ['SUMMIT_12_4_FASTENERS_TPO_M', 'Summit Exteriors', '#12 4 Fasteners - TPO (M)', 'EA', 175.67, ''],
  ['SUMMIT_12_5_FASTENERS_TPO_M', 'Summit Exteriors', '#12 5 Fasteners - TPO (M)', 'EA', 230.67, ''],
  ['SUMMIT_12_6_FASTENERS_TPO_M', 'Summit Exteriors', '#12 6 Fasteners - TPO (M)', 'EA', 224.0, ''],
  ['SUMMIT_12_7_FASTENERS_TPO_M', 'Summit Exteriors', '#12 7 Fasteners - TPO (M)', 'EA', 394.23, ''],
  ['SUMMIT_12_8_FASTENERS_TPO_M', 'Summit Exteriors', '#12 8 Fasteners - TPO (M)', 'EA', 339.0, ''],
  ['SUMMIT_14_10_FASTENER_PER_BOX_500_CT_L', 'Summit Exteriors', '#14 10 Fastener  Per Box - 500 CT (L)', 'EA', 665.0, ''],
  ['SUMMIT_14_12_FASTENERS_PER_BOX_250_CT_M', 'Summit Exteriors', '#14 12 Fasteners  Per Box - 250 CT (M)', 'EA', 405.0, ''],
  ['SUMMIT_14_16_FASTENERS_PER_BOX_250_CT_M', 'Summit Exteriors', '#14 16 Fasteners  Per Box - 250 CT (M)', 'EA', 450.0, ''],
  ['SUMMIT_UPGRADE_OWENS_CORNING_DECORIDGE_HIP_AND_RIDGE_CAP_L', 'Summit Exteriors', '(UPGRADE) OWENS CORNING DECORIDGE HIP AND RIDGE CAP (L)', 'EA', 1.0, ''],
  ['SUMMIT_UPGRADE_OWENS_CORNING_DECORIDGE_HIP_AND_RIDGE_CAP_M', 'Summit Exteriors', '(UPGRADE) OWENS CORNING DECORIDGE HIP AND RIDGE CAP (M)', 'EA', 3.0, ''],
  ['SUMMIT_UPGRADE_OWENS_CORNING_TRUEDEFINITION_DURATION_MAX_SHINGLES_L', 'Summit Exteriors', '(UPGRADE) OWENS CORNING TRUEDEFINITION DURATION MAX SHINGLES (L)', 'EA', 10.0, ''],
  ['SUMMIT_UPGRADE_OWENS_CORNING_TRUEDEFINITION_DURATION_MAX_SHINGLES_M', 'Summit Exteriors', '(UPGRADE) OWENS CORNING TRUEDEFINITION DURATION MAX SHINGLES (M)', 'EA', 75.0, ''],
  ['SUMMIT_UPGRADE_OWENS_CORNING_TRUEDEFINITION_DURATION_SHINGLES_M', 'Summit Exteriors', '(UPGRADE) OWENS CORNING TRUEDEFINITION DURATION SHINGLES (M)', 'EA', 40.0, ''],
  ['SUMMIT_1_1_4_COIL_ROOFING_NAIL_M', 'Summit Exteriors', '1 1/4 COIL ROOFING NAIL (M)', 'EA', 52.4, ''],
  ['SUMMIT_1_3_4_COIL_ROOFING_NAILS_M', 'Summit Exteriors', '1 3/4 COIL ROOFING NAILS (M)', 'EA', 88.99, ''],
  ['SUMMIT_1_SNAPLOCK_PANELS_24GA_L', 'Summit Exteriors', '1 SNAPLOCK PANELS 24GA (L)', 'EA', 2.9, ''],
  ['SUMMIT_1_SNAPLOCK_PANELS_24GA_M', 'Summit Exteriors', '1 SNAPLOCK PANELS 24GA (M)', 'EA', 3.15, ''],
  ['SUMMIT_1_SNAPLOCK_W_NAIL_FLANGE_24GA_L', 'Summit Exteriors', '1 SNAPLOCK W/ NAIL FLANGE 24GA (L)', 'EA', 3.0, ''],
  ['SUMMIT_1_SNAPLOCK_W_NAIL_FLANGE_24GA_M', 'Summit Exteriors', '1 SNAPLOCK W/ NAIL FLANGE 24GA (M)', 'EA', 2.97, ''],
  ['SUMMIT_1_SNAPLOCK_W_NAIL_FLANGE_26GA_L', 'Summit Exteriors', '1 SNAPLOCK W/ NAIL FLANGE 26GA (L)', 'EA', 3.0, ''],
  ['SUMMIT_1_SNAPLOCK_W_NAIL_FLANGE_26GA_M', 'Summit Exteriors', '1 SNAPLOCK W/ NAIL FLANGE 26GA (M)', 'EA', 2.2, ''],
  ['SUMMIT_1_5_MECHANICAL_LOCK_STANDING_SEAM_24GA_METAL_PANELS_L', 'Summit Exteriors', '1.5 MECHANICAL LOCK STANDING SEAM 24GA METAL PANELS (L)', 'EA', 3.5, ''],
  ['SUMMIT_1_5_MECHANICAL_LOCK_STANDING_SEAM_24GA_METAL_PANELS_M', 'Summit Exteriors', '1.5 MECHANICAL LOCK STANDING SEAM 24GA METAL PANELS (M)', 'EA', 2.72, ''],
  ['SUMMIT_1_5_MECHANICAL_LOCK_STANDING_SEAM_26GA_METAL_PANELS_L', 'Summit Exteriors', '1.5 MECHANICAL LOCK STANDING SEAM 26GA METAL PANELS (L)', 'EA', 3.5, ''],
  ['SUMMIT_1_5_MECHANICAL_LOCK_STANDING_SEAM_26GA_METAL_PANELS_M', 'Summit Exteriors', '1.5 MECHANICAL LOCK STANDING SEAM 26GA METAL PANELS (M)', 'EA', 2.5, ''],
  ['SUMMIT_1_5_SNAP_Z_STANDING_SEAM_RIDGE_VENT_M', 'Summit Exteriors', '1.5 SNAP-Z STANDING SEAM RIDGE VENT (M)', 'EA', 6.25, ''],
  ['SUMMIT_1_5_SNAPLOCK_PANELS_24GA_L', 'Summit Exteriors', '1.5 SNAPLOCK PANELS 24GA (L)', 'EA', 2.9, ''],
  ['SUMMIT_1_5_SNAPLOCK_PANELS_24GA_M', 'Summit Exteriors', '1.5 SNAPLOCK PANELS 24GA (M)', 'EA', 3.4, ''],
  ['SUMMIT_1_5_ULTIMATE_PIPE_BOOT_FLASHING_M', 'Summit Exteriors', '1.5 ULTIMATE PIPE BOOT FLASHING (M)', 'EA', 58.0, ''],
  ['SUMMIT_1_2_HD_ISO_COVERBOARD_M', 'Summit Exteriors', '1/2 HD ISO - Coverboard (M)', 'EA', 33.0, ''],
  ['SUMMIT_1_2_PLYWOOD_RESHEET_L', 'Summit Exteriors', '1/2 PLYWOOD RESHEET (L)', 'EA', 30.0, ''],
  ['SUMMIT_1_2_PLYWOOD_RESHEET_M', 'Summit Exteriors', '1/2 PLYWOOD RESHEET (M)', 'EA', 48.45, ''],
  ['SUMMIT_1_8_PLATE_STEEL_GUTTERS_L', 'Summit Exteriors', '1/8 Plate Steel Gutters (L)', 'EA', 10.0, ''],
  ['SUMMIT_1_8_PLATE_STEEL_GUTTERS_M', 'Summit Exteriors', '1/8 Plate Steel Gutters (M)', 'EA', 80.0, ''],
  ['SUMMIT_10_B_VENT_M', 'Summit Exteriors', '10 B-VENT (M)', 'EA', 400.0, ''],
  ['SUMMIT_10_MM_DOUBLE_WALL_POLYCARBONATE_SHEETS_WITH_TRACK_SYSTEM_ONE_TIME_USE_M', 'Summit Exteriors', '10 mm Double wall, polycarbonate sheets with track system-one time use (M)', 'EA', 1260.4, ''],
  ['SUMMIT_14_STEP_FLASHING_M', 'Summit Exteriors', '14 STEP FLASHING (M)', 'EA', 86.75, ''],
  ['SUMMIT_14_SUN_TUNNEL_L', 'Summit Exteriors', '14 Sun Tunnel (L)', 'EA', 250.0, ''],
  ['SUMMIT_14_SUN_TUNNEL_M', 'Summit Exteriors', '14 Sun Tunnel (M)', 'EA', 500.0, ''],
  ['SUMMIT_14GA_PLATE_STEEL_SIDING_L', 'Summit Exteriors', '14GA Plate Steel Siding (L)', 'EA', 5.0, ''],
  ['SUMMIT_14GA_PLATE_STEEL_SIDING_M', 'Summit Exteriors', '14GA Plate Steel Siding (M)', 'EA', 10.0, ''],
  ['SUMMIT_1PC_STANDING_SEAM_CLIP_M', 'Summit Exteriors', '1PC STANDING SEAM CLIP (M)', 'EA', 0.39, ''],
  ['SUMMIT_1X4_PRIMED_FASCIA_L', 'Summit Exteriors', '1x4 PRIMED FASCIA (L)', 'EA', 1.0, ''],
  ['SUMMIT_1X4_PRIMED_FASCIA_M', 'Summit Exteriors', '1x4 PRIMED FASCIA (M)', 'EA', 1.5, ''],
  ['SUMMIT_2_MECHANICAL_LOCK_STANDING_SEAM_24GA_METAL_PANELS_L', 'Summit Exteriors', '2 MECHANICAL LOCK STANDING SEAM 24GA METAL PANELS (L)', 'EA', 3.1, ''],
  ['SUMMIT_2_MECHANICAL_LOCK_STANDING_SEAM_24GA_METAL_PANELS_M', 'Summit Exteriors', '2 MECHANICAL LOCK STANDING SEAM 24GA METAL PANELS (M)', 'EA', 3.59, ''],
  ['SUMMIT_2_RIGID_INSULATION_BOARD_L', 'Summit Exteriors', '2 Rigid Insulation Board (L)', 'EA', 20.0, ''],
  ['SUMMIT_2_RIGID_INSULATION_BOARD_M', 'Summit Exteriors', '2 Rigid Insulation Board (M)', 'EA', 34.0, ''],
  ['SUMMIT_2_SNAP_Z_STANDING_SEAM_RIDGE_VENTS_M', 'Summit Exteriors', '2 SNAP Z STANDING SEAM RIDGE VENTS (M)', 'EA', 7.21, ''],
  ['SUMMIT_2_ULTIMATE_PIPE_BOOT_FLASHING_M', 'Summit Exteriors', '2 ULTIMATE PIPE BOOT FLASHING (M)', 'EA', 58.0, ''],
  ['SUMMIT_2_4_MEMBRANE_PLATES_PER_BOX_1000_CT_M', 'Summit Exteriors', '2.4 Membrane Plates  Per Box - 1000 CT (M)', 'EA', 180.0, ''],
  ['SUMMIT_2_6_ISO_BOARD_4_X8_L', 'Summit Exteriors', '2.6 ISO Board 4\'x8\' (L)', 'EA', 15.0, ''],
  ['SUMMIT_2_6_ISO_BOARD_4_X8_M', 'Summit Exteriors', '2.6 ISO Board 4\'x8\' (M)', 'EA', 48.0, ''],
  ['SUMMIT_22_SUN_TUNNEL_L', 'Summit Exteriors', '22 Sun Tunnel (L)', 'EA', 275.0, ''],
  ['SUMMIT_22_SUN_TUNNEL_M', 'Summit Exteriors', '22 Sun Tunnel (M)', 'EA', 812.0, ''],
  ['SUMMIT_22GA_BEAM_CAP_L', 'Summit Exteriors', '22GA Beam Cap (L)', 'EA', 5.0, ''],
  ['SUMMIT_22GA_BEAM_CAP_M', 'Summit Exteriors', '22GA Beam Cap (M)', 'EA', 5.0, ''],
  ['SUMMIT_22GA_FASCIA_4_FACE_L', 'Summit Exteriors', '22GA Fascia - 4 Face (L)', 'EA', 24.0, ''],
  ['SUMMIT_22GA_FLUSH_WALL_CORTEN_L', 'Summit Exteriors', '22GA Flush Wall - Corten (L)', 'EA', 11.0, ''],
  ['SUMMIT_22GA_FLUSH_WALL_CORTEN_M', 'Summit Exteriors', '22GA Flush Wall - Corten (M)', 'EA', 3.25, ''],
  ['SUMMIT_22GA_KYNAR_WALL_BLOCKS_L', 'Summit Exteriors', '22GA Kynar Wall Blocks (L)', 'EA', 1000.0, ''],
  ['SUMMIT_22GA_KYNAR_WALL_BLOCKS_M', 'Summit Exteriors', '22GA Kynar Wall Blocks (M)', 'EA', 250.0, ''],
  ['SUMMIT_22GA_METAL_FASCIA_DON_T_USE_M', 'Summit Exteriors', '22GA Metal Fascia - Don\'t Use (M)', 'EA', 34.0, ''],
  ['SUMMIT_24_GA_CHIMNEY_CHASE_STAINLESS_STEEL_ONE_TIME_USE_M', 'Summit Exteriors', '24 GA Chimney Chase - Stainless Steel - One Time Use (M)', 'EA', 1150.0, ''],
  ['SUMMIT_24_GA_PARAPET_COPING_DETAIL_3_PAGE_A10_40_SINGLE_USE_L', 'Summit Exteriors', '24 GA Parapet Coping  Detail #3 Page A10.40 - Single Use (L)', 'EA', 6.0, ''],
  ['SUMMIT_24_SIDING_PANELS_DO_NOT_USE_L', 'Summit Exteriors', '24 Siding Panels - Do not use (L)', 'EA', 6.0, ''],
  ['SUMMIT_24_SIDING_PANELS_DO_NOT_USE_M', 'Summit Exteriors', '24 Siding Panels - Do not use (M)', 'EA', 3.25, ''],
  ['SUMMIT_24_TPO_PERMITER_FLASHING_M', 'Summit Exteriors', '24 TPO Permiter Flashing (M)', 'EA', 465.0, ''],
  ['SUMMIT_24_W_VALLEY_METAL_FLASHING_L', 'Summit Exteriors', '24 W VALLEY METAL FLASHING (L)', 'EA', 12.0, ''],
  ['SUMMIT_24_W_VALLEY_METAL_FLASHING_M', 'Summit Exteriors', '24 W VALLEY METAL FLASHING (M)', 'EA', 36.57, ''],
  ['SUMMIT_24GA_CUSTOM_CHIMNEY_FLASHING_L', 'Summit Exteriors', '24GA CUSTOM CHIMNEY FLASHING (L)', 'EA', 350.0, ''],
  ['SUMMIT_24GA_CUSTOM_CHIMNEY_FLASHING_M', 'Summit Exteriors', '24GA CUSTOM CHIMNEY FLASHING (M)', 'EA', 216.2, ''],
  ['SUMMIT_24GA_CUSTOM_CHIMNEY_WRAP_AND_CAP_L', 'Summit Exteriors', '24GA CUSTOM CHIMNEY WRAP AND CAP (L)', 'EA', 1000.0, ''],
  ['SUMMIT_24GA_CUSTOM_CHIMNEY_WRAP_AND_CAP_M', 'Summit Exteriors', '24GA CUSTOM CHIMNEY WRAP AND CAP (M)', 'EA', 1500.0, ''],
  ['SUMMIT_24GA_CUSTOM_SKYLIGHT_FLASHING_L', 'Summit Exteriors', '24GA CUSTOM SKYLIGHT FLASHING (L)', 'EA', 300.0, ''],
  ['SUMMIT_24GA_CUSTOM_SKYLIGHT_FLASHING_M', 'Summit Exteriors', '24GA CUSTOM SKYLIGHT FLASHING (M)', 'EA', 252.0, ''],
  ['SUMMIT_24GA_FLUSH_WALL_PANELS_DO_NOT_USE_L', 'Summit Exteriors', '24GA Flush Wall Panels - Do not use (L)', 'EA', 6.0, ''],
  ['SUMMIT_24GA_FLUSH_WALL_PANELS_DO_NOT_USE_M', 'Summit Exteriors', '24GA Flush Wall Panels - Do not use (M)', 'EA', 3.5, ''],
  ['SUMMIT_24GA_MATTE_BLACK_WESTERN_RIB_SIDING_36COVERAGE_L', 'Summit Exteriors', '24GA Matte black Western Rib Siding 36Coverage (L)', 'EA', 4.0, ''],
  ['SUMMIT_24GA_MATTE_BLACK_WESTERN_RIB_SIDING_36COVERAGE_M', 'Summit Exteriors', '24GA Matte black Western Rib Siding 36Coverage (M)', 'EA', 2.4, ''],
  ['SUMMIT_24GA_SIDING_PACKAGE_DO_NOT_USE_M', 'Summit Exteriors', '24GA Siding Package - Do not use (M)', 'EA', 23615.0, ''],
  ['SUMMIT_24GA_STANDING_SEAM_UPGRADE_L', 'Summit Exteriors', '24GA Standing Seam Upgrade (L)', 'EA', 20.0, ''],
  ['SUMMIT_24GA_STANDING_SEAM_UPGRADE_M', 'Summit Exteriors', '24GA Standing Seam Upgrade (M)', 'EA', 50.0, ''],
  ['SUMMIT_24GA_TRIMS_DO_NOT_USE_M', 'Summit Exteriors', '24GA Trims - Do not use (M)', 'EA', 3.5, ''],
  ['SUMMIT_24GA_UPGRADE_L', 'Summit Exteriors', '24GA Upgrade (L)', 'EA', 20.0, ''],
  ['SUMMIT_24GA_UPGRADE_M', 'Summit Exteriors', '24GA Upgrade (M)', 'EA', 50.0, ''],
  ['SUMMIT_26GA_CUSTOM_CHIMNEY_L', 'Summit Exteriors', '26GA CUSTOM CHIMNEY (L)', 'EA', 350.0, ''],
  ['SUMMIT_26GA_CUSTOM_CHIMNEY_M', 'Summit Exteriors', '26GA CUSTOM CHIMNEY (M)', 'EA', 158.0, ''],
  ['SUMMIT_26GA_CUSTOM_CHIMNEY_WRAP_AND_CAP_L', 'Summit Exteriors', '26GA CUSTOM CHIMNEY WRAP AND CAP (L)', 'EA', 1000.0, ''],
  ['SUMMIT_26GA_CUSTOM_CHIMNEY_WRAP_AND_CAP_M', 'Summit Exteriors', '26GA CUSTOM CHIMNEY WRAP AND CAP (M)', 'EA', 1500.0, ''],
  ['SUMMIT_26GA_CUSTOM_SKYLIGHT_FLASHING_L', 'Summit Exteriors', '26GA CUSTOM SKYLIGHT FLASHING (L)', 'EA', 300.0, ''],
  ['SUMMIT_26GA_CUSTOM_SKYLIGHT_FLASHING_M', 'Summit Exteriors', '26GA CUSTOM SKYLIGHT FLASHING (M)', 'EA', 210.0, ''],
  ['SUMMIT_26GA_PBR_PANELS', 'Summit Exteriors', '26GA PBR Panels', 'EA', 1.35, ''],
  ['SUMMIT_26GA_PBR_PANELS_L', 'Summit Exteriors', '26GA PBR Panels. (L)', 'EA', 2.0, ''],
  ['SUMMIT_26GA_PBR_PANELS_M', 'Summit Exteriors', '26GA PBR Panels. (M)', 'EA', 1.31, ''],
  ['SUMMIT_29GA_MATCHED_METAL_PANELS_M', 'Summit Exteriors', '29GA Matched Metal Panels (M)', 'EA', 1974.0, ''],
  ['SUMMIT_2ND_STORY_LABOR_L', 'Summit Exteriors', '2ND STORY LABOR (L)', 'EA', 20.0, ''],
  ['SUMMIT_2X3_SECOND_STORY_DOWNSPOUT_L', 'Summit Exteriors', '2X3 SECOND STORY DOWNSPOUT (L)', 'EA', 75.0, ''],
  ['SUMMIT_2X3_SECOND_STORY_DOWNSPOUT_M', 'Summit Exteriors', '2X3 SECOND STORY DOWNSPOUT (M)', 'EA', 51.21, ''],
  ['SUMMIT_2X3_SINGLE_STORY_DOWNSPOUT_L', 'Summit Exteriors', '2X3 SINGLE STORY DOWNSPOUT (L)', 'EA', 37.5, ''],
  ['SUMMIT_2X3_SINGLE_STORY_DOWNSPOUT_M', 'Summit Exteriors', '2X3 SINGLE STORY DOWNSPOUT (M)', 'EA', 38.41, ''],
  ['SUMMIT_2X3_THIRD_STORY_DOWNSPOUT_L', 'Summit Exteriors', '2X3 THIRD STORY DOWNSPOUT (L)', 'EA', 112.5, ''],
  ['SUMMIT_2X3_THIRD_STORY_DOWNSPOUT_M', 'Summit Exteriors', '2X3 THIRD STORY DOWNSPOUT (M)', 'EA', 65.7, ''],
  ['SUMMIT_2ND_STORY_GUTTER_CHARGE_M', 'Summit Exteriors', '2nd Story Gutter Charge (M)', 'EA', 1.0, ''],
  ['SUMMIT_3_INSULATION_PLATES_M', 'Summit Exteriors', '3 Insulation Plates (M)', 'EA', 219.0, ''],
  ['SUMMIT_3_NAILBASE_INSULATED_L', 'Summit Exteriors', '3 Nailbase - Insulated (L)', 'EA', 15.0, ''],
  ['SUMMIT_3_NAILBASE_INSULATED_M', 'Summit Exteriors', '3 Nailbase - Insulated (M)', 'EA', 60.0, ''],
  ['SUMMIT_3_ULTIMATE_PIPE_BOOT_FLASHING_M', 'Summit Exteriors', '3 ULTIMATE PIPE BOOT FLASHING (M)', 'EA', 58.0, ''],
  ['SUMMIT_3_16_PARAPET_COPING_DO_NOT_USE_L', 'Summit Exteriors', '3/16 Parapet Coping - Do not use (L)', 'EA', 10.0, ''],
  ['SUMMIT_3_16_PARAPET_COPING_DO_NOT_USE_M', 'Summit Exteriors', '3/16 Parapet Coping - Do not use (M)', 'EA', 80.0, ''],
  ['SUMMIT_3_16_PLATE_STEEL_FASCIA_L', 'Summit Exteriors', '3/16 Plate Steel Fascia (L)', 'EA', 10.0, ''],
  ['SUMMIT_3_16_PLATE_STEEL_FASCIA_M', 'Summit Exteriors', '3/16 Plate Steel Fascia (M)', 'EA', 65.0, ''],
  ['SUMMIT_3RD_STORY_LABOR_L', 'Summit Exteriors', '3RD STORY LABOR (L)', 'EA', 20.0, ''],
  ['SUMMIT_3X4_SECOND_STORY_DOWNSPOUT_L', 'Summit Exteriors', '3X4 SECOND STORY DOWNSPOUT (L)', 'EA', 75.0, ''],
  ['SUMMIT_3X4_SECOND_STORY_DOWNSPOUT_M', 'Summit Exteriors', '3X4 SECOND STORY DOWNSPOUT (M)', 'EA', 74.4, ''],
  ['SUMMIT_3X4_SINGLE_STORY_DOWNSPOUT_L', 'Summit Exteriors', '3X4 SINGLE STORY DOWNSPOUT (L)', 'EA', 37.5, ''],
  ['SUMMIT_3X4_SINGLE_STORY_DOWNSPOUT_M', 'Summit Exteriors', '3X4 SINGLE STORY DOWNSPOUT (M)', 'EA', 37.2, ''],
  ['SUMMIT_3X4_THIRD_STORY_DOWNSPOUT_L', 'Summit Exteriors', '3X4 THIRD STORY DOWNSPOUT (L)', 'EA', 112.5, ''],
  ['SUMMIT_3X4_THIRD_STORY_DOWNSPOUT_M', 'Summit Exteriors', '3X4 THIRD STORY DOWNSPOUT (M)', 'EA', 111.6, ''],
  ['SUMMIT_4_METAL_STEM_VENT_M', 'Summit Exteriors', '4 METAL STEM VENT (M)', 'EA', 32.0, ''],
  ['SUMMIT_4_ULTIMATE_PIPE_BOOT_FLASHING_M', 'Summit Exteriors', '4 ULTIMATE PIPE BOOT FLASHING (M)', 'EA', 58.0, ''],
  ['SUMMIT_4_5_INSULATIONS_BOARD_M', 'Summit Exteriors', '4.5 Insulations Board (M)', 'EA', 150.0, ''],
  ['SUMMIT_4MM_ACM_DO_NOT_USE_M', 'Summit Exteriors', '4MM ACM - Do not use (M)', 'EA', 10.0, ''],
  ['SUMMIT_4TH_STORY_LABOR_L', 'Summit Exteriors', '4TH STORY LABOR (L)', 'EA', 60.0, ''],
  ['SUMMIT_4X10_CORTEN_PLATES_M', 'Summit Exteriors', '4x10\' Corten Plates (M)', 'EA', 125.0, ''],
  ['SUMMIT_5_ALUMINUM_SEAMLESS_GUTTERS_L', 'Summit Exteriors', '5 ALUMINUM SEAMLESS GUTTERS (L)', 'EA', 3.0, ''],
  ['SUMMIT_5_ALUMINUM_SEAMLESS_GUTTERS_M', 'Summit Exteriors', '5 ALUMINUM SEAMLESS GUTTERS (M)', 'EA', 2.2, ''],
  ['SUMMIT_5_EXTRA_DOWNSPOUT_L', 'Summit Exteriors', '5 EXTRA DOWNSPOUT (L)', 'EA', 2.5, ''],
  ['SUMMIT_5_EXTRA_DOWNSPOUT_M', 'Summit Exteriors', '5 EXTRA DOWNSPOUT (M)', 'EA', 1.46, ''],
  ['SUMMIT_5_GUTTER_CORNER_L', 'Summit Exteriors', '5 GUTTER CORNER (L)', 'EA', 15.0, ''],
  ['SUMMIT_5_GUTTER_CORNER_M', 'Summit Exteriors', '5 GUTTER CORNER (M)', 'EA', 2.26, ''],
  ['SUMMIT_5_8_OSB_RESHEET_L', 'Summit Exteriors', '5/8 OSB RESHEET (L)', 'EA', 30.0, ''],
  ['SUMMIT_5_8_OSB_RESHEET_M', 'Summit Exteriors', '5/8 OSB RESHEET (M)', 'EA', 21.6, ''],
  ['SUMMIT_5_8_OSB_SINGLE_BOARD_REMOVE_AND_REPLACE_L', 'Summit Exteriors', '5/8 OSB SINGLE BOARD REMOVE AND REPLACE (L)', 'EA', 30.0, ''],
  ['SUMMIT_5_8_OSB_SINGLE_BOARD_REMOVE_AND_REPLACE_M', 'Summit Exteriors', '5/8 OSB SINGLE BOARD REMOVE AND REPLACE (M)', 'EA', 22.0, ''],
  ['SUMMIT_6_ALUMINUM_SEAMLESS_GUTTERS_L', 'Summit Exteriors', '6 ALUMINUM SEAMLESS GUTTERS (L)', 'EA', 3.0, ''],
  ['SUMMIT_6_ALUMINUM_SEAMLESS_GUTTERS_M', 'Summit Exteriors', '6 ALUMINUM SEAMLESS GUTTERS (M)', 'EA', 2.8, ''],
  ['SUMMIT_6_EXTRA_DOWNSPOUT_L', 'Summit Exteriors', '6 EXTRA DOWNSPOUT (L)', 'EA', 2.5, ''],
  ['SUMMIT_6_EXTRA_DOWNSPOUT_M', 'Summit Exteriors', '6 EXTRA DOWNSPOUT (M)', 'EA', 2.48, ''],
  ['SUMMIT_6_GALVALUME_GUTTERS_L', 'Summit Exteriors', '6 GALVALUME GUTTERS (L)', 'EA', 2.5, ''],
  ['SUMMIT_6_GALVALUME_GUTTERS_M', 'Summit Exteriors', '6 GALVALUME GUTTERS (M)', 'EA', 3.3, ''],
  ['SUMMIT_6_GUTTER_CORNER_L', 'Summit Exteriors', '6 GUTTER CORNER (L)', 'EA', 15.0, ''],
  ['SUMMIT_6_GUTTER_CORNER_M', 'Summit Exteriors', '6 GUTTER CORNER (M)', 'EA', 4.75, ''],
  ['SUMMIT_6_HALF_ROUND_SEAMLESS_GUTTERS_AND_DOWNSPOUTS_M', 'Summit Exteriors', '6 Half Round Seamless Gutters and Downspouts (M)', 'EA', 32.0, ''],
  ['SUMMIT_6_METAL_STEM_VENT_M', 'Summit Exteriors', '6 METAL STEM VENT (M)', 'EA', 39.0, ''],
  ['SUMMIT_6_8_B_VENT_L', 'Summit Exteriors', '6-8 B-VENT (L)', 'EA', 20.0, ''],
  ['SUMMIT_6_8_B_VENT_M', 'Summit Exteriors', '6-8 B-VENT (M)', 'EA', 130.0, ''],
  ['SUMMIT_7_8_COIL_ROOFING_NAIL_M', 'Summit Exteriors', '7/8 COIL ROOFING NAIL (M)', 'EA', 57.0, ''],
  ['SUMMIT_7_8_CORRUGATED_24GA_L', 'Summit Exteriors', '7/8 Corrugated 24GA (L)', 'EA', 6.0, ''],
  ['SUMMIT_7_8_CORRUGATED_24GA_M', 'Summit Exteriors', '7/8 Corrugated 24GA (M)', 'EA', 2.57, ''],
  ['SUMMIT_8_B_VENT_M', 'Summit Exteriors', '8 B-VENT (M)', 'EA', 400.0, ''],
  ['SUMMIT_8_STEP_FLASHING_M', 'Summit Exteriors', '8 STEP FLASHING (M)', 'EA', 68.9, ''],
  ['SUMMIT_ACM_SIDING_FASCIA_DO_NOT_USE_L', 'Summit Exteriors', 'ACM Siding/Fascia - Do not use (L)', 'EA', 23.0, ''],
  ['SUMMIT_ACM_SIDING_FASCIA_DO_NOT_USE_M', 'Summit Exteriors', 'ACM Siding/Fascia - Do not use (M)', 'EA', 9.0, ''],
  ['SUMMIT_ADDITIONAL_LAYER_TEAR_OFF_L', 'Summit Exteriors', 'ADDITIONAL LAYER TEAR OFF (L)', 'EA', 25.0, ''],
  ['SUMMIT_ALUREX_DOUBLE_PRO_GUTTER_GUARD_L', 'Summit Exteriors', 'ALUREX DOUBLE PRO GUTTER GUARD (L)', 'EA', 3.0, ''],
  ['SUMMIT_ALUREX_DOUBLE_PRO_GUTTER_GUARD_M', 'Summit Exteriors', 'ALUREX DOUBLE PRO GUTTER GUARD (M)', 'EA', 4.0, ''],
  ['SUMMIT_ALUREX_T_REX_GUTTER_GUARDS_L', 'Summit Exteriors', 'ALUREX T-REX GUTTER GUARDS (L)', 'EA', 3.0, ''],
  ['SUMMIT_ALUREX_T_REX_GUTTER_GUARDS_M', 'Summit Exteriors', 'ALUREX T-REX GUTTER GUARDS (M)', 'EA', 2.15, ''],
  ['SUMMIT_ARCHITECTURAL_PEAK_FLASHING_24GA_M', 'Summit Exteriors', 'ARCHITECTURAL PEAK FLASHING 24GA (M)', 'EA', 39.3, ''],
  ['SUMMIT_ARCHITECTURAL_PEAK_FLASHING_26GA_M', 'Summit Exteriors', 'ARCHITECTURAL PEAK FLASHING 26GA (M)', 'EA', 30.59, ''],
  ['SUMMIT_ARCHITECTURAL_RAKE_GABLE_24GA_M', 'Summit Exteriors', 'ARCHITECTURAL RAKE/GABLE 24GA (M)', 'EA', 32.5, ''],
  ['SUMMIT_ARCHITECTURAL_RAKE_GABLE_26GA_M', 'Summit Exteriors', 'ARCHITECTURAL RAKE/GABLE 26GA (M)', 'EA', 23.5, ''],
  ['SUMMIT_AGWEST_LABOR', 'Summit Exteriors', 'Agwest Labor', 'EA', 20000.0, ''],
  ['SUMMIT_ALPINE_SNOWGUARD_SNOMAX_L', 'Summit Exteriors', 'Alpine Snowguard Snomax (L)', 'EA', 5.0, ''],
  ['SUMMIT_ALPINE_SNOWGUARD_SNOMAX_M', 'Summit Exteriors', 'Alpine Snowguard Snomax (M)', 'EA', 20.0, ''],
  ['SUMMIT_ALUMINUM_SOFFIT_TAYLOR_METALS_L', 'Summit Exteriors', 'Aluminum Soffit Taylor Metals (L)', 'EA', 300.0, ''],
  ['SUMMIT_ALUMINUM_SOFFIT_TAYLOR_METALS_M', 'Summit Exteriors', 'Aluminum Soffit Taylor Metals (M)', 'EA', 507.0, ''],
  ['SUMMIT_AWARD_METALS_CHIMNEY_SADDLE', 'Summit Exteriors', 'Award Metals Chimney Saddle', 'EA', 40.0, ''],
  ['SUMMIT_AWARD_METALS_GALVANIZED_FLAT_SHINGLE', 'Summit Exteriors', 'Award Metals Galvanized Flat Shingle', 'EA', 68.25, ''],
  ['SUMMIT_AWARD_METALS_ROOF_TO_WALL_FLASHING', 'Summit Exteriors', 'Award Metals Roof to Wall Flashing', 'EA', 22.95, ''],
  ['SUMMIT_AWARD_METALS_STYLE_D_EAVE_DRIP', 'Summit Exteriors', 'Award Metals Style-D Eave Drip', 'EA', 19.0, ''],
  ['SUMMIT_AWARD_METALS_W_VALLEY_FLASHING', 'Summit Exteriors', 'Award Metals W-Valley Flashing', 'EA', 34.5, ''],
  ['SUMMIT_BRAVA_1_75_HDG_RING_SHANK_COIL_NAILS_M', 'Summit Exteriors', 'BRAVA 1.75 HDG RING SHANK COIL NAILS (M)', 'EA', 152.28, ''],
  ['SUMMIT_BRAVA_12_STANDARD_SLATE_M', 'Summit Exteriors', 'BRAVA 12 STANDARD SLATE (M)', 'EA', 50.68, ''],
  ['SUMMIT_BRAVA_3_HDG_RING_SHANK_HAND_NAILS_M', 'Summit Exteriors', 'BRAVA 3 HDG RING SHANK HAND NAILS (M)', 'EA', 47.75, ''],
  ['SUMMIT_BRAVA_INSTALLATION_LABOR_L', 'Summit Exteriors', 'BRAVA INSTALLATION LABOR (L)', 'EA', 400.0, ''],
  ['SUMMIT_BRAVA_LOW_E_UNDERLAYMENT_M', 'Summit Exteriors', 'BRAVA LOW E UNDERLAYMENT (M)', 'EA', 245.0, ''],
  ['SUMMIT_BRAVA_SEAM_TAPE_L', 'Summit Exteriors', 'BRAVA SEAM TAPE (L)', 'EA', 10.0, ''],
  ['SUMMIT_BRAVA_TILE_HIP_AND_RIDGE_LOW_SLOPE_M', 'Summit Exteriors', 'BRAVA TILE HIP AND RIDGE - LOW SLOPE (M)', 'EA', 68.64, ''],
  ['SUMMIT_BRAVA_TILE_HIP_AND_RIDGE_CAP_M', 'Summit Exteriors', 'BRAVA TILE HIP AND RIDGE CAP (M)', 'EA', 68.64, ''],
  ['SUMMIT_BRAVA_TILE_STARTER_M', 'Summit Exteriors', 'BRAVA TILE STARTER (M)', 'EA', 51.29, ''],
  ['SUMMIT_BACKER_ROD_M', 'Summit Exteriors', 'Backer Rod (M)', 'EA', 0.1, ''],
  ['SUMMIT_BLACK_OXIDE_10_1_12_PAN_HEADS_M', 'Summit Exteriors', 'Black Oxide #10 1/12 Pan Heads (M)', 'EA', 490.0, ''],
  ['SUMMIT_BOARD_AND_BATTEN_SIDING_M', 'Summit Exteriors', 'Board and Batten siding (M)', 'EA', 2.21, ''],
  ['SUMMIT_BOX_GUTTERS_DO_NOT_USE_L', 'Summit Exteriors', 'Box Gutters - Do not use (L)', 'EA', 10.0, ''],
  ['SUMMIT_BOX_GUTTERS_DO_NOT_USE_M', 'Summit Exteriors', 'Box Gutters - Do not use (M)', 'EA', 15.0, ''],
  ['SUMMIT_BRAVA_MATERIAL_PACKAGE_JOB_SPECIFIC_M', 'Summit Exteriors', 'Brava Material Package - Job Specific (M)', 'EA', 36127.0, ''],
  ['SUMMIT_BRAVA_RIDGE_BDL_M', 'Summit Exteriors', 'Brava Ridge BDL (M)', 'EA', 79.25, ''],
  ['SUMMIT_BRAVA_SHAKE_M', 'Summit Exteriors', 'Brava Shake (M)', 'EA', 6.12, ''],
  ['SUMMIT_BRAVA_SHAKE_BDL_M', 'Summit Exteriors', 'Brava Shake BDL (M)', 'EA', 670.0, ''],
  ['SUMMIT_BRAVA_SHAKE_BUNDLE_GEE_M', 'Summit Exteriors', 'Brava Shake Bundle Gee (M)', 'EA', 670.0, ''],
  ['SUMMIT_BRAVA_SHAKE_SQ_GEE_L', 'Summit Exteriors', 'Brava Shake SQ (Gee) (L)', 'EA', 400.0, ''],
  ['SUMMIT_BRAVA_SHAKE_SQ_GEE_M', 'Summit Exteriors', 'Brava Shake SQ (Gee) (M)', 'EA', 670.0, ''],
  ['SUMMIT_BRAVA_STARTER_GEE_M', 'Summit Exteriors', 'Brava Starter Gee (M)', 'EA', 57.0, ''],
  ['SUMMIT_C_CHANNEL_24_GA_M', 'Summit Exteriors', 'C Channel 24 GA (M)', 'EA', 2.25, ''],
  ['SUMMIT_C01_SKYLIGHT_FIXED_M', 'Summit Exteriors', 'C01 Skylight Fixed (M)', 'EA', 600.0, ''],
  ['SUMMIT_C04_SKYLIGHT_FIXED_M', 'Summit Exteriors', 'C04 Skylight (fixed) (M)', 'EA', 648.0, ''],
  ['SUMMIT_CAP_NAILS_M', 'Summit Exteriors', 'CAP NAILS (M)', 'EA', 33.99, ''],
  ['SUMMIT_CATCH_BASIN_M', 'Summit Exteriors', 'CATCH BASIN (M)', 'EA', 200.0, ''],
  ['SUMMIT_CEDAR_SHAKE_REMOVAL_L', 'Summit Exteriors', 'CEDAR SHAKE REMOVAL (L)', 'EA', 25.0, ''],
  ['SUMMIT_CEDAR_SHAKE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_L', 'Summit Exteriors', 'CEDAR SHAKE TEAR OFF AND DISPOSAL (SINGLE LAYER) (L)', 'EA', 50.0, ''],
  ['SUMMIT_CEDAR_SHAKE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_M', 'Summit Exteriors', 'CEDAR SHAKE TEAR OFF AND DISPOSAL (SINGLE LAYER) (M)', 'EA', 8.0, ''],
  ['SUMMIT_CERTAINTEED_GRANDMANOR_SHINGLES_M', 'Summit Exteriors', 'CERTAINTEED GRANDMANOR SHINGLES (M)', 'EA', 240.0, ''],
  ['SUMMIT_CERTAINTEED_MOUNTAIN_RIDGE_CAP_M', 'Summit Exteriors', 'CERTAINTEED MOUNTAIN RIDGE CAP (M)', 'EA', 80.1, ''],
  ['SUMMIT_CERTAINTEED_PRESIDENTIAL_SHAKE_L', 'Summit Exteriors', 'CERTAINTEED PRESIDENTIAL SHAKE (L)', 'EA', 18.0, ''],
  ['SUMMIT_CERTAINTEED_PRESIDENTIAL_SHAKE_M', 'Summit Exteriors', 'CERTAINTEED PRESIDENTIAL SHAKE (M)', 'EA', 46.0, ''],
  ['SUMMIT_CERTAINTEED_PRESIDENTIAL_STARTER_M', 'Summit Exteriors', 'CERTAINTEED PRESIDENTIAL STARTER (M)', 'EA', 91.6, ''],
  ['SUMMIT_CERTAINTEED_PRESIDENTIAL_TL_SHINGLE_L', 'Summit Exteriors', 'CERTAINTEED PRESIDENTIAL TL SHINGLE (L)', 'EA', 26.6, ''],
  ['SUMMIT_CERTAINTEED_PRESIDENTIAL_TL_SHINGLE_M', 'Summit Exteriors', 'CERTAINTEED PRESIDENTIAL TL SHINGLE (M)', 'EA', 40.0, ''],
  ['SUMMIT_CERTAINTEED_SWIFT_START_STARTER_M', 'Summit Exteriors', 'CERTAINTEED SWIFT START STARTER (M)', 'EA', 61.3, ''],
  ['SUMMIT_CHIMNEY_REMOVAL_L', 'Summit Exteriors', 'CHIMNEY REMOVAL (L)', 'EA', 150.0, ''],
  ['SUMMIT_CHIMNEY_REMOVAL_M', 'Summit Exteriors', 'CHIMNEY REMOVAL (M)', 'EA', 50.0, ''],
  ['SUMMIT_CLEAT_24GA_M', 'Summit Exteriors', 'CLEAT 24GA (M)', 'EA', 8.5, ''],
  ['SUMMIT_CLEAT_26GA_M', 'Summit Exteriors', 'CLEAT 26GA (M)', 'EA', 5.8, ''],
  ['SUMMIT_CUTTING_IN_LOG_SIDING_WALL_FLASHING_L', 'Summit Exteriors', 'CUTTING IN LOG SIDING WALL FLASHING (L)', 'EA', 8.0, ''],
  ['SUMMIT_CUTTING_IN_RIDGE_VENT_L', 'Summit Exteriors', 'CUTTING IN RIDGE VENT (L)', 'EA', 2.0, ''],
  ['SUMMIT_CAULK_FASTENERS_MISC_SUPPLIES_M', 'Summit Exteriors', 'Caulk/Fasteners/Misc Supplies (M)', 'EA', 3000.0, ''],
  ['SUMMIT_CEDAR_INSTALL_L', 'Summit Exteriors', 'Cedar Install (L)', 'EA', 5.64, ''],
  ['SUMMIT_CEDUR_PACKAGE_DO_NOT_USE', 'Summit Exteriors', 'Cedur Package - Do not use', 'EA', 5000.0, ''],
  ['SUMMIT_CERTAINTEED_DIAMONDDECK_SYNTHETIC_UNDERLAYMENT_ABC', 'Summit Exteriors', 'CertainTeed DiamondDeck Synthetic Underlayment (ABC)', 'EA', 192.0, ''],
  ['SUMMIT_CLEAR_CORRUGATED_POLYCARBONATE_ROOF_PANELS_M', 'Summit Exteriors', 'Clear Corrugated Polycarbonate Roof Panels (M)', 'EA', 39.98, ''],
  ['SUMMIT_COPPER_FLATS_M', 'Summit Exteriors', 'Copper Flats (M)', 'EA', 350.0, ''],
  ['SUMMIT_COPPER_RIDGE_STRIP_L', 'Summit Exteriors', 'Copper Ridge Strip (L)', 'EA', 1.98, ''],
  ['SUMMIT_COPPER_RIDGE_STRIP_M', 'Summit Exteriors', 'Copper Ridge Strip (M)', 'EA', 2.75, ''],
  ['SUMMIT_COPPER_UPGRADE_L', 'Summit Exteriors', 'Copper Upgrade (L)', 'EA', 2.0, ''],
  ['SUMMIT_COPPER_UPGRADE_M', 'Summit Exteriors', 'Copper Upgrade (M)', 'EA', 10.0, ''],
  ['SUMMIT_CORTEN_FASCIA_M', 'Summit Exteriors', 'Corten Fascia (M)', 'EA', 42.0, ''],
  ['SUMMIT_CORTEN_WALL_PANELS_BARRON_M', 'Summit Exteriors', 'Corten Wall Panels - Barron (M)', 'EA', 200045.0, ''],
  ['SUMMIT_CORTEN_WALL_SECTIONS_ADU_BARRON_M', 'Summit Exteriors', 'Corten Wall Sections ADU - Barron (M)', 'EA', 1892.0, ''],
  ['SUMMIT_COST_DIFFERENCE_FOR_GAF_UHDZ_DON_T_USE_M', 'Summit Exteriors', 'Cost Difference For GAF UHDZ - Don\'t Use (M)', 'EA', 15.0, ''],
  ['SUMMIT_COVERLITE_CORRUGATED_POLYCARBONATE_ONE_TIME_USE_M', 'Summit Exteriors', 'CoverLite Corrugated Polycarbonate **One time use (M)', 'EA', 80.56, ''],
  ['SUMMIT_CURB_METAL_DETAIL_SINGLE_USE_L', 'Summit Exteriors', 'Curb Metal Detail - Single Use (L)', 'EA', 50.0, ''],
  ['SUMMIT_CURB_METAL_DETAIL_SINGLE_USE_M', 'Summit Exteriors', 'Curb Metal Detail - Single Use (M)', 'EA', 53.0, ''],
  ['SUMMIT_CUSTOM_TRIM_DON_T_USE_M', 'Summit Exteriors', 'Custom Trim - Don\'t Use (M)', 'EA', 24.0, ''],
  ['SUMMIT_CUSTOM_VENTING_DO_NOT_USE_L', 'Summit Exteriors', 'Custom Venting - Do not use (L)', 'EA', 10.0, ''],
  ['SUMMIT_CUSTOM_VENTING_DO_NOT_USE_M', 'Summit Exteriors', 'Custom Venting - Do not use (M)', 'EA', 7.0, ''],
  ['SUMMIT_CUSTOM_WALL_FLASHING_ONE_TIME_USE_M', 'Summit Exteriors', 'Custom Wall Flashing - One time use (M)', 'EA', 3.0, ''],
  ['SUMMIT_CUSTOM_WALL_FLASHING_ONE_TIME_M', 'Summit Exteriors', 'Custom Wall flashing - ONE TIME (M)', 'EA', 2.5, ''],
  ['SUMMIT_CUT_EDGE_SEALANT_M', 'Summit Exteriors', 'Cut Edge Sealant (M)', 'EA', 16.0, ''],
  ['SUMMIT_D_STYLE_DRIP_EDGE_FLASHING_M', 'Summit Exteriors', 'D-STYLE DRIP EDGE FLASHING (M)', 'EA', 8.5, ''],
  ['SUMMIT_DECRA_MATERIAL_AND_LABOR_L', 'Summit Exteriors', 'DECRA MATERIAL AND LABOR (L)', 'EA', 300.0, ''],
  ['SUMMIT_DAVINCI_SLATE_INSTALL_DO_NOT_USE_L', 'Summit Exteriors', 'Davinci Slate Install - Do not use (L)', 'EA', 26730.0, ''],
  ['SUMMIT_DAVINCI_SLATE_INSTALL_DO_NOT_USE_M', 'Summit Exteriors', 'Davinci Slate Install - Do not use (M)', 'EA', 74031.0, ''],
  ['SUMMIT_DELORES_DEPOT_TAPER_PACKAGE_L', 'Summit Exteriors', 'Delores Depot Taper Package (L)', 'EA', 2.0, ''],
  ['SUMMIT_DELORES_DEPOT_TAPER_PACKAGE_M', 'Summit Exteriors', 'Delores Depot Taper Package (M)', 'EA', 2.9, ''],
  ['SUMMIT_DETAIL_MEMBRANE_M', 'Summit Exteriors', 'Detail membrane (M)', 'EA', 500.0, ''],
  ['SUMMIT_DRY_IN_CUSTOMER_SUPPLIED_MATERIAL_L', 'Summit Exteriors', 'Dry-In Customer Supplied Material (L)', 'EA', 25.0, ''],
  ['SUMMIT_DYNAMIC_DENTAL_WARRANTY', 'Summit Exteriors', 'Dynamic Dental Warranty', 'EA', 1000.0, ''],
  ['SUMMIT_EDGE_TRIMS_M', 'Summit Exteriors', 'Edge Trims (M)', 'EA', 3.0, ''],
  ['SUMMIT_EXPOSED_FASTENER_SIDING_LABOR_L', 'Summit Exteriors', 'Exposed Fastener Siding Labor (L)', 'EA', 2100.0, ''],
  ['SUMMIT_EXPOSED_FASTNER_DRIP_EDGE_M', 'Summit Exteriors', 'Exposed fastner drip edge (M)', 'EA', 9.34, ''],
  ['SUMMIT_FRAMING_A_CRICKET_L', 'Summit Exteriors', 'FRAMING A CRICKET (L)', 'EA', 100.0, ''],
  ['SUMMIT_FRAMING_A_CRICKET_M', 'Summit Exteriors', 'FRAMING A CRICKET (M)', 'EA', 50.0, ''],
  ['SUMMIT_FUSION_GUARD_SNOW_PADS_L', 'Summit Exteriors', 'FUSION GUARD SNOW PADS (L)', 'EA', 1.5, ''],
  ['SUMMIT_FUSION_GUARD_SNOW_PADS_M', 'Summit Exteriors', 'FUSION GUARD SNOW PADS (M)', 'EA', 6.04, ''],
  ['SUMMIT_FANFOLD_FP_38_M', 'Summit Exteriors', 'Fanfold FP 38 (M)', 'EA', 138.0, ''],
  ['SUMMIT_FASCIA_CALGARY_L', 'Summit Exteriors', 'Fascia -Calgary (L)', 'EA', 5.0, ''],
  ['SUMMIT_FASCIA_CALGARY_M', 'Summit Exteriors', 'Fascia -Calgary (M)', 'EA', 3.0, ''],
  ['SUMMIT_FASCIA_22GA_L', 'Summit Exteriors', 'Fascia 22GA (L)', 'EA', 5.0, ''],
  ['SUMMIT_FASCIA_22GA_M', 'Summit Exteriors', 'Fascia 22GA (M)', 'EA', 3.0, ''],
  ['SUMMIT_FASCIA_INSTALLATION_STACKED_METAL_WRAP_STACKED_METAL_FASCIA_ON_2X8_OVER_2X12_SUB_FASCIA_L', 'Summit Exteriors', 'Fascia Installation - Stacked Metal Wrap Stacked metal fascia on 2x8 over 2x12 sub fascia (L)', 'EA', 8.0, ''],
  ['SUMMIT_FASCIA_INSTALLATION_STACKED_METAL_WRAP_STACKED_METAL_FASCIA_ON_2X8_OVER_2X12_SUB_FASCIA_M', 'Summit Exteriors', 'Fascia Installation - Stacked Metal Wrap Stacked metal fascia on 2x8 over 2x12 sub fascia (M)', 'EA', 3.65, ''],
  ['SUMMIT_FASCIA_INSTALLATION_26GA_METAL_FASICA_FOR_A_2X8_SUB_FASCIA_L', 'Summit Exteriors', 'Fascia Installation 26GA metal fasica for a 2x8 sub fascia (L)', 'EA', 5.0, ''],
  ['SUMMIT_FASCIA_INSTALLATION_26GA_METAL_FASICA_FOR_A_2X8_SUB_FASCIA_M', 'Summit Exteriors', 'Fascia Installation 26GA metal fasica for a 2x8 sub fascia (M)', 'EA', 1.88, ''],
  ['SUMMIT_FASCIA_LABOR_L', 'Summit Exteriors', 'Fascia Labor (L)', 'EA', 7680.0, ''],
  ['SUMMIT_FAST_VENT_PLUS_M', 'Summit Exteriors', 'Fast Vent Plus (M)', 'EA', 6.4, ''],
  ['SUMMIT_FLAT_PAN_INSTALL_L', 'Summit Exteriors', 'Flat Pan Install (L)', 'EA', 1.0, ''],
  ['SUMMIT_FLATS_26GA_M', 'Summit Exteriors', 'Flats 26GA (M)', 'EA', 60.0, ''],
  ['SUMMIT_FLUSH_PANELS_AEP_SPAN_FLEX_L', 'Summit Exteriors', 'Flush Panels/AEP Span Flex (L)', 'EA', 9.0, ''],
  ['SUMMIT_FLUSH_PANELS_AEP_SPAN_FLEX_M', 'Summit Exteriors', 'Flush Panels/AEP Span Flex (M)', 'EA', 5.5, ''],
  ['SUMMIT_GAF_WEATHERWATCH_ICE_WATER_LEAK_BARRIER_ABC', 'Summit Exteriors', 'GAF WeatherWatch Ice & Water Leak Barrier (ABC)', 'EA', 136.5, ''],
  ['SUMMIT_GUTTER_CLEAN_SYSTEM_M', 'Summit Exteriors', 'GUTTER CLEAN SYSTEM (M)', 'EA', 2.25, ''],
  ['SUMMIT_GUTTER_REMOVAL_DISPOSAL_L', 'Summit Exteriors', 'GUTTER REMOVAL + DISPOSAL (L)', 'EA', 1.0, ''],
  ['SUMMIT_GUTTER_WEDGES_L', 'Summit Exteriors', 'GUTTER WEDGES (L)', 'EA', 0.5, ''],
  ['SUMMIT_GUTTER_WEDGES_M', 'Summit Exteriors', 'GUTTER WEDGES (M)', 'EA', 0.67, ''],
  ['SUMMIT_HAND_LOAD_L', 'Summit Exteriors', 'HAND LOAD (L)', 'EA', 36.0, ''],
  ['SUMMIT_HANDYMAN_JOB_DO_NOT_USE_L', 'Summit Exteriors', 'Handyman Job - Do not use (L)', 'EA', 5000.0, ''],
  ['SUMMIT_HARDIE_SIDING_PACKAGE_M', 'Summit Exteriors', 'Hardie Siding Package (M)', 'EA', 49180.0, ''],
  ['SUMMIT_HIGH_TEMP_ICE_AND_WATER_M', 'Summit Exteriors', 'High Temp Ice and Water (M)', 'EA', 130.69, ''],
  ['SUMMIT_HORIZONTAL_SIDING_L', 'Summit Exteriors', 'Horizontal Siding (L)', 'EA', 4.0, ''],
  ['SUMMIT_HORIZONTAL_SIDING_M', 'Summit Exteriors', 'Horizontal Siding (M)', 'EA', 2.4, ''],
  ['SUMMIT_IBEX_1_4_HEX_SCREWS_M', 'Summit Exteriors', 'IBEX 1/4 HEX SCREWS (M)', 'EA', 20.4, ''],
  ['SUMMIT_IBEX_29GA_TUFF_RIB_PANELS_L', 'Summit Exteriors', 'IBEX 29GA TUFF RIB PANELS (L)', 'EA', 2.3, ''],
  ['SUMMIT_IBEX_29GA_TUFF_RIB_PANELS_M', 'Summit Exteriors', 'IBEX 29GA TUFF RIB PANELS (M)', 'EA', 1.2, ''],
  ['SUMMIT_IBEX_D_DRIP_EDGE_29GA_M', 'Summit Exteriors', 'IBEX D DRIP EDGE 29GA (M)', 'EA', 6.7, ''],
  ['SUMMIT_IBEX_DRIP_EDGE_29GA_M', 'Summit Exteriors', 'IBEX Drip Edge 29GA (M)', 'EA', 7.34, ''],
  ['SUMMIT_IBEX_ENDWALL_FLASHING_29GA_M', 'Summit Exteriors', 'IBEX ENDWALL FLASHING 29GA (M)', 'EA', 17.1, ''],
  ['SUMMIT_IBEX_GABLE_29GA_M', 'Summit Exteriors', 'IBEX Gable 29GA (M)', 'EA', 14.15, ''],
  ['SUMMIT_IBEX_METAL_DELIVERY_M', 'Summit Exteriors', 'IBEX METAL DELIVERY (M)', 'EA', 300.0, ''],
  ['SUMMIT_IBEX_METAL_FASCIA_M', 'Summit Exteriors', 'IBEX Metal Fascia (M)', 'EA', 11.42, ''],
  ['SUMMIT_IBEX_PEAK_FLASHING_29GA_M', 'Summit Exteriors', 'IBEX PEAK FLASHING 29GA (M)', 'EA', 19.93, ''],
  ['SUMMIT_IBEX_PITCH_BREAK_TRANSITION_29GA_M', 'Summit Exteriors', 'IBEX PITCH BREAK TRANSITION 29GA (M)', 'EA', 17.1, ''],
  ['SUMMIT_IBEX_RAKE_GABLE_29GA_M', 'Summit Exteriors', 'IBEX RAKE/GABLE 29GA (M)', 'EA', 15.6, ''],
  ['SUMMIT_IBEX_RIDGE_CAP_29GA_M', 'Summit Exteriors', 'IBEX RIDGE CAP 29GA (M)', 'EA', 22.0, ''],
  ['SUMMIT_IBEX_ROLL_FLOVENT_M', 'Summit Exteriors', 'IBEX ROLL FLOVENT (M)', 'EA', 39.21, ''],
  ['SUMMIT_IBEX_SIDEWALL_FLASHING_29GA_M', 'Summit Exteriors', 'IBEX SIDEWALL FLASHING 29GA (M)', 'EA', 16.96, ''],
  ['SUMMIT_IBEX_VALLEY_METAL_29GA_M', 'Summit Exteriors', 'IBEX VALLEY METAL 29GA (M)', 'EA', 28.3, ''],
  ['SUMMIT_ICE_AND_WATER_SHIELD_M', 'Summit Exteriors', 'ICE AND WATER SHIELD (M)', 'EA', 74.2, ''],
  ['SUMMIT_IKO_AR_ARMOURSHAKE_SHINGLES_L', 'Summit Exteriors', 'IKO AR ARMOURSHAKE SHINGLES (L)', 'EA', 18.0, ''],
  ['SUMMIT_IKO_AR_ARMOURSHAKE_SHINGLES_M', 'Summit Exteriors', 'IKO AR ARMOURSHAKE SHINGLES (M)', 'EA', 40.39, ''],
  ['SUMMIT_IKO_ARMOUR_STARTER_M', 'Summit Exteriors', 'IKO ARMOUR STARTER (M)', 'EA', 125.02, ''],
  ['SUMMIT_IKO_DYNASTY_AR_SHINGLES_L', 'Summit Exteriors', 'IKO DYNASTY AR SHINGLES (L)', 'EA', 28.3, ''],
  ['SUMMIT_IKO_DYNASTY_AR_SHINGLES_M', 'Summit Exteriors', 'IKO DYNASTY AR SHINGLES (M)', 'EA', 51.41, ''],
  ['SUMMIT_IKO_ULTRA_HP_HIP_AND_RIDGE_CAP_M', 'Summit Exteriors', 'IKO ULTRA HP HIP AND RIDGE CAP (M)', 'EA', 104.7, ''],
  ['SUMMIT_INSTALL_TPO_ROOF_LABOR_L', 'Summit Exteriors', 'INSTALL TPO ROOF LABOR (L)', 'EA', 120.0, ''],
  ['SUMMIT_INSTALL_TPO_ROOF_LABOR_DO_NOT_USE_L', 'Summit Exteriors', 'INSTALL TPO ROOF LABOR - Do not use (L)', 'EA', 120.0, ''],
  ['SUMMIT_INSTALL_TPO_ROOF_LABOR_DON_T_USE_L', 'Summit Exteriors', 'INSTALL TPO ROOF LABOR - Don\'t Use (L)', 'EA', 200.0, ''],
  ['SUMMIT_INSTALL_TPO_ROOF_LABOR_COVERS_THE_COST_OF_TIME_AND_LABOR_OF_INSTALLATION_OF_A_TPO_ROOF_SYSTEM_L', 'Summit Exteriors', 'INSTALL TPO ROOF LABOR Covers the cost of time and labor of  installation of a TPO Roof System (L)', 'EA', 12500.0, ''],
  ['SUMMIT_IPS_PIPE_BOOT_FLASHING_M', 'Summit Exteriors', 'IPS PIPE BOOT FLASHING (M)', 'EA', 10.5, ''],
  ['SUMMIT_IBEX_SNAPLOCK_LABOR_ONLY_L', 'Summit Exteriors', 'Ibex Snaplock Labor Only (L)', 'EA', 270.0, ''],
  ['SUMMIT_IN_HOUSE_LABOR_H2B_MAN_HOUR_L', 'Summit Exteriors', 'In-House Labor - H2B Man Hour (L)', 'EA', 33.0, ''],
  ['SUMMIT_IN_HOUSE_LABOR_METAL_DAILY_7_MAN_CREW_L', 'Summit Exteriors', 'In-House Labor Metal Daily - 7 Man Crew (L)', 'EA', 2020.0, ''],
  ['SUMMIT_IN_HOUSE_MANAGER_DAY_RATE_L', 'Summit Exteriors', 'In-House Manager - Day Rate (L)', 'EA', 389.0, ''],
  ['SUMMIT_INSULATION_PACKAGE_R_30', 'Summit Exteriors', 'Insulation Package R-30', 'EA', 108.0, ''],
  ['SUMMIT_INSULATION_R_49_ONE_TIME_USE_M', 'Summit Exteriors', 'Insulation R-49 - One time use (M)', 'EA', 5.98, ''],
  ['SUMMIT_INSULATION_TAPE_M', 'Summit Exteriors', 'Insulation Tape (M)', 'EA', 23.0, ''],
  ['SUMMIT_J_CHANNEL_MINI_M', 'Summit Exteriors', 'J Channel - Mini (M)', 'EA', 8.0, ''],
  ['SUMMIT_J_CHANNEL_24_GA_M', 'Summit Exteriors', 'J Channel 24 GA (M)', 'EA', 1.9, ''],
  ['SUMMIT_JELLYFISH_LABOR_L', 'Summit Exteriors', 'JELLYFISH LABOR (L)', 'EA', 5.75, ''],
  ['SUMMIT_JELLYFISH_MARK_5_LIGHT_STRANDS_M', 'Summit Exteriors', 'JELLYFISH MARK 5 LIGHT STRANDS (M)', 'EA', 7.6, ''],
  ['SUMMIT_JELLYFISH_MISC_SUPPLIES_M', 'Summit Exteriors', 'JELLYFISH MISC SUPPLIES (M)', 'EA', 75.0, ''],
  ['SUMMIT_JELLYFISH_NO_ACCESS_CHARGE_L', 'Summit Exteriors', 'JELLYFISH NO ACCESS CHARGE (L)', 'EA', 3.0, ''],
  ['SUMMIT_JELLYFISH_OUTDOOR_EAVE_LIGHT_48V_CONTROLLER_M', 'Summit Exteriors', 'JELLYFISH OUTDOOR EAVE LIGHT 48V CONTROLLER (M)', 'EA', 720.0, ''],
  ['SUMMIT_JELLYFISH_POWER_SUPPLY_M', 'Summit Exteriors', 'JELLYFISH POWER SUPPLY (M)', 'EA', 380.0, ''],
  ['SUMMIT_JELLYFISH_RECEIVER_TRANSMITTER_M', 'Summit Exteriors', 'JELLYFISH RECEIVER/TRANSMITTER (M)', 'EA', 31.8, ''],
  ['SUMMIT_JELLYFISH_SPECIALTY_CLIPS_M', 'Summit Exteriors', 'JELLYFISH SPECIALTY CLIPS (M)', 'EA', 1.17, ''],
  ['SUMMIT_JELLYFISH_SPECIALTY_TRACK_M', 'Summit Exteriors', 'JELLYFISH SPECIALTY TRACK (M)', 'EA', 19.24, ''],
  ['SUMMIT_JELLYFISH_STANDARD_CLIPS_M', 'Summit Exteriors', 'JELLYFISH STANDARD CLIPS (M)', 'EA', 0.95, ''],
  ['SUMMIT_JELLYFISH_STANDARD_TRACK_M', 'Summit Exteriors', 'JELLYFISH STANDARD TRACK (M)', 'EA', 13.3, ''],
  ['SUMMIT_JELLYFISH_SYSTEM_CONTROLLER_M', 'Summit Exteriors', 'JELLYFISH SYSTEM CONTROLLER (M)', 'EA', 572.0, ''],
  ['SUMMIT_JELLYFISH_WIFI_RANGE_EXTENDER_L', 'Summit Exteriors', 'JELLYFISH WIFI RANGE EXTENDER (L)', 'EA', 80.0, ''],
  ['SUMMIT_JELLYFISH_WIFI_RANGE_EXTENDER_M', 'Summit Exteriors', 'JELLYFISH WIFI RANGE EXTENDER (M)', 'EA', 69.0, ''],
  ['SUMMIT_JOP_TRAINING_HATES_SKYRIGHT_L', 'Summit Exteriors', 'Jop Training - hates skyright (L)', 'EA', 130.0, ''],
  ['SUMMIT_KOOTENAI_COUNTY_AREA_PERMIT_M', 'Summit Exteriors', 'KOOTENAI COUNTY AREA PERMIT (M)', 'EA', 12.0, ''],
  ['SUMMIT_KOOTENAI_COUNTY_DUMP_FEES_M', 'Summit Exteriors', 'KOOTENAI COUNTY DUMP FEES (M)', 'EA', 6.0, ''],
  ['SUMMIT_KUMA_SNOW_DESTROYER_M', 'Summit Exteriors', 'Kuma Snow Destroyer (M)', 'EA', 250.0, ''],
  ['SUMMIT_LARGE_CHIMNEY_RE_FLASH_L', 'Summit Exteriors', 'LARGE CHIMNEY RE-FLASH (L)', 'EA', 300.0, ''],
  ['SUMMIT_LARGE_CHIMNEY_RE_FLASH_M', 'Summit Exteriors', 'LARGE CHIMNEY RE-FLASH (M)', 'EA', 30.0, ''],
  ['SUMMIT_LIFT_RENTAL_M', 'Summit Exteriors', 'LIFT RENTAL (M)', 'EA', 1500.0, ''],
  ['SUMMIT_LIMITED_ACCESS_L', 'Summit Exteriors', 'LIMITED ACCESS (L)', 'EA', 12.0, ''],
  ['SUMMIT_LOW_SLOPE_ICE_AND_WATER_SHIELD_M', 'Summit Exteriors', 'LOW SLOPE ICE AND WATER SHIELD (M)', 'EA', 74.2, ''],
  ['SUMMIT_LABOR_ONLY_METAL_INSTALL_DO_NOT_USE_L', 'Summit Exteriors', 'Labor Only Metal Install - Do not use (L)', 'EA', 300.0, ''],
  ['SUMMIT_LEAF_BLASTER_PRO_5_GUTTER_GUARDS_1PC_IS_4_FT_M', 'Summit Exteriors', 'Leaf Blaster Pro 5 Gutter Guards   *1pc is 4 ft (M)', 'EA', 10.71, ''],
  ['SUMMIT_LIFETIME_TOOL_PIPE_FLASHING_150_ULTIMATE', 'Summit Exteriors', 'Lifetime Tool Pipe Flashing 150 Ultimate', 'EA', 75.0, ''],
  ['SUMMIT_LIFETIME_TOOL_PIPE_FLASHING_200_ULTIMATE', 'Summit Exteriors', 'Lifetime Tool Pipe Flashing 200 Ultimate', 'EA', 75.0, ''],
  ['SUMMIT_LIFETIME_TOOL_PIPE_FLASHING_300_ULTIMATE', 'Summit Exteriors', 'Lifetime Tool Pipe Flashing 300 Ultimate', 'EA', 90.0, ''],
  ['SUMMIT_LIFETIME_TOOL_PIPE_FLASHING_400_ULTIMATE', 'Summit Exteriors', 'Lifetime Tool Pipe Flashing 400 Ultimate', 'EA', 90.0, ''],
  ['SUMMIT_LIFT_TRANSPORT_L', 'Summit Exteriors', 'Lift Transport (L)', 'EA', 600.0, ''],
  ['SUMMIT_LIGHT_SHELF_WRAPPING_L', 'Summit Exteriors', 'Light Shelf Wrapping (L)', 'EA', 3500.0, ''],
  ['SUMMIT_LIGHT_SHELF_WRAPPING_M', 'Summit Exteriors', 'Light Shelf Wrapping (M)', 'EA', 1500.0, ''],
  ['SUMMIT_LOMANCO_EAVE_HEADWALL_VENT_STRIP_L', 'Summit Exteriors', 'Lomanco Eave/Headwall Vent Strip (L)', 'EA', 2.0, ''],
  ['SUMMIT_LOMANCO_EAVE_HEADWALL_VENT_STRIP_M', 'Summit Exteriors', 'Lomanco Eave/Headwall Vent Strip (M)', 'EA', 17.0, ''],
  ['SUMMIT_LOMANCO_OR4_LO_OMNIRIDGE_VENT', 'Summit Exteriors', 'Lomanco OR4 Lo-OmniRidge Vent', 'EA', 31.0, ''],
  ['SUMMIT_LUX_VERTICAL_SIDING_L', 'Summit Exteriors', 'Lux Vertical Siding (L)', 'EA', 6.0, ''],
  ['SUMMIT_LUX_VERTICAL_SIDING_M', 'Summit Exteriors', 'Lux Vertical Siding (M)', 'EA', 8.0, ''],
  ['SUMMIT_LVL_FASCIA_DO_NOT_USE_M', 'Summit Exteriors', 'LvL Fascia - do not use (M)', 'EA', 12.0, ''],
  ['SUMMIT_M08_COMBI_INSTALL_L', 'Summit Exteriors', 'M08 Combi-install (L)', 'EA', 150.0, ''],
  ['SUMMIT_M08_COMBI_INSTALL_M', 'Summit Exteriors', 'M08 Combi-install (M)', 'EA', 699.0, ''],
  ['SUMMIT_METAL_ATTIC_BOX_VENTS_M', 'Summit Exteriors', 'METAL ATTIC BOX VENTS (M)', 'EA', 15.0, ''],
  ['SUMMIT_METAL_PIPE_FLASHING_L', 'Summit Exteriors', 'METAL PIPE FLASHING (L)', 'EA', 25.0, ''],
  ['SUMMIT_METAL_PIPE_FLASHING_M', 'Summit Exteriors', 'METAL PIPE FLASHING (M)', 'EA', 15.0, ''],
  ['SUMMIT_METAL_STEEP_PITCH_10_12_L', 'Summit Exteriors', 'METAL STEEP PITCH 10/12 (L)', 'EA', 40.0, ''],
  ['SUMMIT_METAL_STEEP_PITCH_12_12_L', 'Summit Exteriors', 'METAL STEEP PITCH 12/12 (L)', 'EA', 60.0, ''],
  ['SUMMIT_METAL_STEEP_PITCH_7_12_L', 'Summit Exteriors', 'METAL STEEP PITCH 7/12 (L)', 'EA', 10.0, ''],
  ['SUMMIT_METAL_STEEP_PITCH_8_12_L', 'Summit Exteriors', 'METAL STEEP PITCH 8/12 (L)', 'EA', 20.0, ''],
  ['SUMMIT_METAL_STEEP_PITCH_9_12_L', 'Summit Exteriors', 'METAL STEEP PITCH 9/12 (L)', 'EA', 30.0, ''],
  ['SUMMIT_METAL_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_L', 'Summit Exteriors', 'METAL TEAR OFF AND DISPOSAL (SINGLE LAYER) (L)', 'EA', 60.0, ''],
  ['SUMMIT_METAL_VALLEY_24GA_L', 'Summit Exteriors', 'METAL VALLEY 24GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_METAL_VALLEY_24GA_M', 'Summit Exteriors', 'METAL VALLEY 24GA (M)', 'EA', 60.42, ''],
  ['SUMMIT_METAL_VALLEY_26GA_L', 'Summit Exteriors', 'METAL VALLEY 26GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_METAL_VALLEY_26GA_M', 'Summit Exteriors', 'METAL VALLEY 26GA (M)', 'EA', 49.51, ''],
  ['SUMMIT_MILEAGE_CHARGE_L', 'Summit Exteriors', 'MILEAGE CHARGE (L)', 'EA', 30.0, ''],
  ['SUMMIT_MTL4_TRIM_BANDS_M', 'Summit Exteriors', 'MTL4 Trim Bands (M)', 'EA', 3.0, ''],
  ['SUMMIT_METAL_CREW_MILEAGE', 'Summit Exteriors', 'Metal Crew Mileage', 'EA', 25.0, ''],
  ['SUMMIT_METAL_LABOR_BASE_RATE_SNAPLOCK_L', 'Summit Exteriors', 'Metal Labor - Base Rate Snaplock (L)', 'EA', 100.0, ''],
  ['SUMMIT_METAL_SALES_VERTICAL_SEAM_24GA_18_COVERAGE_1_75_RIB_CLIPPED_INSTALLATION_M', 'Summit Exteriors', 'Metal Sales Vertical Seam  24GA 18 Coverage 1.75 Rib Clipped Installation (M)', 'EA', 2.68, ''],
  ['SUMMIT_METAL_SIDING_PACKAGE_26GA_BOARD_AND_BAT_CORRUGATED_PBR_AG_PANEL_L', 'Summit Exteriors', 'Metal Siding Package   26GA - Board and Bat, Corrugated, PBR, Ag Panel (L)', 'EA', 25000.0, ''],
  ['SUMMIT_METAL_SIDING_PACKAGE_26GA_BOARD_AND_BAT_CORRUGATED_PBR_AG_PANEL_M', 'Summit Exteriors', 'Metal Siding Package   26GA - Board and Bat, Corrugated, PBR, Ag Panel (M)', 'EA', 20000.0, ''],
  ['SUMMIT_METAL_SIDING_PACKAGE_24GA_WESTERN_WAVE_WSMR_L', 'Summit Exteriors', 'Metal Siding Package  24GA Western Wave - WSMR (L)', 'EA', 40000.0, ''],
  ['SUMMIT_METAL_SIDING_PACKAGE_24GA_WESTERN_WAVE_WSMR_M', 'Summit Exteriors', 'Metal Siding Package  24GA Western Wave - WSMR (M)', 'EA', 30000.0, ''],
  ['SUMMIT_METAL_SIDING_PACKAGE_DO_NOT_USE_M', 'Summit Exteriors', 'Metal Siding Package - Do not use (M)', 'EA', 14068.0, ''],
  ['SUMMIT_METAL_SOFFIT_INSTALLATION_29_METAL_SOFFIT_L', 'Summit Exteriors', 'Metal Soffit Installation 29 Metal Soffit (L)', 'EA', 5.0, ''],
  ['SUMMIT_METAL_SOFFIT_INSTALLATION_29_METAL_SOFFIT_M', 'Summit Exteriors', 'Metal Soffit Installation 29 Metal Soffit (M)', 'EA', 1.66, ''],
  ['SUMMIT_METAL_SPIRE_L', 'Summit Exteriors', 'Metal Spire (L)', 'EA', 2500.0, ''],
  ['SUMMIT_METAL_SPIRE_M', 'Summit Exteriors', 'Metal Spire (M)', 'EA', 1000.0, ''],
  ['SUMMIT_METAL_TRIMS_PACKAGE_DO_NOT_USE_M', 'Summit Exteriors', 'Metal Trims Package - Do not use (M)', 'EA', 1000.0, ''],
  ['SUMMIT_METAL_V_GROOVE_SOFFIT_26GA_MEASURED_BY_THE_SQFT_M', 'Summit Exteriors', 'Metal V-Groove Soffit 26GA **Measured by the SQFT (M)', 'EA', 2.55, ''],
  ['SUMMIT_OFFSET_CLEAT_24GA_M', 'Summit Exteriors', 'OFFSET CLEAT 24GA (M)', 'EA', 14.3, ''],
  ['SUMMIT_OFFSET_CLEAT_26GA_M', 'Summit Exteriors', 'OFFSET CLEAT 26GA (M)', 'EA', 11.2, ''],
  ['SUMMIT_OPEN_HEMS_RIDGE_CAP_24GA_M', 'Summit Exteriors', 'OPEN HEMS RIDGE CAP 24GA (M)', 'EA', 44.5, ''],
  ['SUMMIT_OPEN_HEMS_RIDGE_CAP_26GA_M', 'Summit Exteriors', 'OPEN HEMS RIDGE CAP 26GA (M)', 'EA', 32.35, ''],
  ['SUMMIT_OSB_LAYOVER_L', 'Summit Exteriors', 'OSB LAYOVER (L)', 'EA', 20.0, ''],
  ['SUMMIT_OSB_LAYOVER_M', 'Summit Exteriors', 'OSB LAYOVER (M)', 'EA', 17.0, ''],
  ['SUMMIT_OWENS_CORNING_DECK_SEAL_MA_NAILBASE_L', 'Summit Exteriors', 'OWENS CORNING DECK SEAL MA NAILBASE (L)', 'EA', 240.0, ''],
  ['SUMMIT_OWENS_CORNING_DECK_SEAL_MA_NAILBASE_M', 'Summit Exteriors', 'OWENS CORNING DECK SEAL MA NAILBASE (M)', 'EA', 126.4, ''],
  ['SUMMIT_OWENS_CORNING_DECK_SEAL_SBS_SA_CAP_2_PART_SYSTEM_M', 'Summit Exteriors', 'OWENS CORNING DECK SEAL SBS SA CAP (2 PART SYSTEM) (M)', 'EA', 151.58, ''],
  ['SUMMIT_OWENS_CORNING_DECORIDGE_HIP_AND_RIDGE_CAP_L', 'Summit Exteriors', 'OWENS CORNING DECORIDGE HIP AND RIDGE CAP (L)', 'EA', 20.0, ''],
  ['SUMMIT_OWENS_CORNING_DECORIDGE_HIP_AND_RIDGE_CAP_M', 'Summit Exteriors', 'OWENS CORNING DECORIDGE HIP AND RIDGE CAP (M)', 'EA', 107.59, ''],
  ['SUMMIT_OWENS_CORNING_OAKRIDGE_SHINGLES_L', 'Summit Exteriors', 'OWENS CORNING OAKRIDGE SHINGLES (L)', 'EA', 23.33, ''],
  ['SUMMIT_OWENS_CORNING_OAKRIDGE_SHINGLES_M', 'Summit Exteriors', 'OWENS CORNING OAKRIDGE SHINGLES (M)', 'EA', 38.85, ''],
  ['SUMMIT_OWENS_CORNING_PREFERRED_PROTECTION_WARRANTY_M', 'Summit Exteriors', 'OWENS CORNING PREFERRED PROTECTION WARRANTY (M)', 'EA', 14.0, ''],
  ['SUMMIT_OWENS_CORNING_PROEDGE_HIP_AND_RIDGE_CAP_M', 'Summit Exteriors', 'OWENS CORNING PROEDGE HIP AND RIDGE CAP (M)', 'EA', 88.43, ''],
  ['SUMMIT_OWENS_CORNING_STARTER_STRIP_PLUS_M', 'Summit Exteriors', 'OWENS CORNING STARTER STRIP PLUS (M)', 'EA', 60.04, ''],
  ['SUMMIT_OWENS_CORNING_TRUEDEFINITION_DURATION_MAX_SHINGLES_L', 'Summit Exteriors', 'OWENS CORNING TRUEDEFINITION DURATION MAX SHINGLES (L)', 'EA', 20.0, ''],
  ['SUMMIT_OWENS_CORNING_TRUEDEFINITION_DURATION_MAX_SHINGLES_M', 'Summit Exteriors', 'OWENS CORNING TRUEDEFINITION DURATION MAX SHINGLES (M)', 'EA', 45.0, ''],
  ['SUMMIT_OWENS_CORNING_TRUEDEFINITION_DURATION_SHINGLES_L', 'Summit Exteriors', 'OWENS CORNING TRUEDEFINITION DURATION SHINGLES (L)', 'EA', 24.0, ''],
  ['SUMMIT_OWENS_CORNING_TRUEDEFINITION_DURATION_SHINGLES_M', 'Summit Exteriors', 'OWENS CORNING TRUEDEFINITION DURATION SHINGLES (M)', 'EA', 48.16, ''],
  ['SUMMIT_OWENS_CORNING_VENTSURE_STRIP_L', 'Summit Exteriors', 'OWENS CORNING VENTSURE STRIP (L)', 'EA', 2.0, ''],
  ['SUMMIT_OWENS_CORNING_VENTSURE_STRIP_M', 'Summit Exteriors', 'OWENS CORNING VENTSURE STRIP (M)', 'EA', 16.37, ''],
  ['SUMMIT_OWENS_CORNING_WOOD_CREST_SHINGLES_L', 'Summit Exteriors', 'OWENS CORNING WOOD CREST SHINGLES (L)', 'EA', 18.0, ''],
  ['SUMMIT_OWENS_CORNING_WOOD_CREST_SHINGLES_M', 'Summit Exteriors', 'OWENS CORNING WOOD CREST SHINGLES (M)', 'EA', 42.93, ''],
  ['SUMMIT_OWENS_CORNING_OAKRIDGE_ARCHITECTURAL_SHINGLES_ABC', 'Summit Exteriors', 'Owens Corning Oakridge Architectural Shingles (ABC)', 'EA', 141.99, ''],
  ['SUMMIT_OWENS_CORNING_PROEDGE_HIP_RIDGE_SHINGLES_ABC', 'Summit Exteriors', 'Owens Corning ProEdge Hip & Ridge Shingles (ABC)', 'EA', 98.33, ''],
  ['SUMMIT_OWENS_CORNING_RHINOROOF_GRANULATED_SA_UNDERLAYMENT', 'Summit Exteriors', 'Owens Corning RhinoRoof Granulated SA Underlayment', 'EA', 91.0, ''],
  ['SUMMIT_OWENS_CORNING_RHINOROOF_GRANULATED_SA_UNDERLAYMENT_ABC', 'Summit Exteriors', 'Owens Corning RhinoRoof Granulated SA Underlayment (ABC)', 'EA', 91.0, ''],
  ['SUMMIT_OWENS_CORNING_RHINOROOF_U20_SYNTHETIC_UNDERLAYMENT', 'Summit Exteriors', 'Owens Corning RhinoRoof U20 Synthetic Underlayment', 'EA', 104.0, ''],
  ['SUMMIT_OWENS_CORNING_STARTER_STRIP_PLUS_SHINGLE_ABC', 'Summit Exteriors', 'Owens Corning Starter Strip Plus Shingle (ABC)', 'EA', 82.33, ''],
  ['SUMMIT_OWENS_CORNING_TRUDEFINITION_DURATION_ARCHITECTURAL_SHINGLES', 'Summit Exteriors', 'Owens Corning TruDefinition Duration Architectural Shingles', 'EA', 148.99, ''],
  ['SUMMIT_OWENS_CORNING_TRUDEFINITION_DURATION_DESIGNER_ARCHITECTURAL_SHINGLES_ABC', 'Summit Exteriors', 'Owens Corning TruDefinition Duration Designer Architectural Shingles (ABC)', 'EA', 148.99, ''],
  ['SUMMIT_OWENS_CORNING_VENTSURE_RIDGE_VENT_ABC', 'Summit Exteriors', 'Owens Corning VentSure Ridge Vent (ABC)', 'EA', 115.5, ''],
  ['SUMMIT_PANCAKE_SCREWS_M', 'Summit Exteriors', 'PANCAKE SCREWS (M)', 'EA', 19.9, ''],
  ['SUMMIT_PBR_PANEL_24_GAUGE_L', 'Summit Exteriors', 'PBR Panel 24 Gauge (L)', 'EA', 2.2, ''],
  ['SUMMIT_PBR_PANEL_24_GAUGE_M', 'Summit Exteriors', 'PBR Panel 24 Gauge (M)', 'EA', 2.52, ''],
  ['SUMMIT_POWER_MAST_FLASHING_M', 'Summit Exteriors', 'POWER MAST FLASHING (M)', 'EA', 61.0, ''],
  ['SUMMIT_PREMIUM_SHINGLE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_L', 'Summit Exteriors', 'PREMIUM SHINGLE TEAR OFF AND DISPOSAL (SINGLE LAYER) (L)', 'EA', 70.0, ''],
  ['SUMMIT_PREMIUM_SHINGLE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_M', 'Summit Exteriors', 'PREMIUM SHINGLE TEAR OFF AND DISPOSAL (SINGLE LAYER) (M)', 'EA', 8.0, ''],
  ['SUMMIT_PVC_MEMBRANE_5_X100_M', 'Summit Exteriors', 'PVC Membrane 5\'x100\' (M)', 'EA', 882.0, ''],
  ['SUMMIT_PVC_ROOF_LABOR', 'Summit Exteriors', 'PVC Roof Labor', 'EA', 75000.0, ''],
  ['SUMMIT_PVC_TRIMS_L', 'Summit Exteriors', 'PVC Trims (L)', 'EA', 5.0, ''],
  ['SUMMIT_PVC_TRIMS_M', 'Summit Exteriors', 'PVC Trims (M)', 'EA', 3.0, ''],
  ['SUMMIT_PVC_WALKPAD_M', 'Summit Exteriors', 'PVC Walkpad (M)', 'EA', 545.0, ''],
  ['SUMMIT_PANELS_AND_TRIMS_DO_NOT_USE_M', 'Summit Exteriors', 'Panels and trims - Do not use (M)', 'EA', 1408.75, ''],
  ['SUMMIT_PARAPET_COPING_22GA_DO_NOT_USE_M', 'Summit Exteriors', 'Parapet Coping 22GA - Do not use (M)', 'EA', 5.75, ''],
  ['SUMMIT_PARAPET_METAL_24GA_L', 'Summit Exteriors', 'Parapet Metal - 24GA (L)', 'EA', 5.0, ''],
  ['SUMMIT_PARAPET_METAL_24GA_M', 'Summit Exteriors', 'Parapet Metal - 24GA (M)', 'EA', 11.0, ''],
  ['SUMMIT_PER_DIEM_DO_NOT_USE_L', 'Summit Exteriors', 'Per Diem - Do not use (L)', 'EA', 85.0, ''],
  ['SUMMIT_PLATE_FABRICATION_LABOR_M', 'Summit Exteriors', 'Plate Fabrication Labor (M)', 'EA', 30.0, ''],
  ['SUMMIT_POLYISO_BOARD_4_X8_2_M', 'Summit Exteriors', 'Polyiso Board 4\'x8\' 2 (M)', 'EA', 28.0, ''],
  ['SUMMIT_POWDER_COATING_S5_M', 'Summit Exteriors', 'Powder Coating S5 (M)', 'EA', 45.0, ''],
  ['SUMMIT_PREVAILING_WAGE_HOURS_DO_NOT_USE_L', 'Summit Exteriors', 'Prevailing Wage Hours - Do not use (L)', 'EA', 45.0, ''],
  ['SUMMIT_PRINT_SIDING_PACKAGE_L', 'Summit Exteriors', 'Print Siding Package (L)', 'EA', 8800.0, ''],
  ['SUMMIT_PRINT_SIDING_PACKAGE_M', 'Summit Exteriors', 'Print Siding Package (M)', 'EA', 22000.0, ''],
  ['SUMMIT_REPAIR_IBEX_1_5_SNAPLOCK_PANELS_24GA_M', 'Summit Exteriors', 'REPAIR IBEX 1.5 SNAPLOCK PANELS 24GA (M)', 'EA', 2.75, ''],
  ['SUMMIT_ROLL_METAL_FLASHING', 'Summit Exteriors', 'ROLL METAL FLASHING', 'EA', 84.96, ''],
  ['SUMMIT_ROOF_PLUG_KWIK_M', 'Summit Exteriors', 'ROOF PLUG KWIK (M)', 'EA', 16.69, ''],
  ['SUMMIT_RAIN_CHAIN_OUTLET_M', 'Summit Exteriors', 'Rain Chain Outlet (M)', 'EA', 35.0, ''],
  ['SUMMIT_REMOVE_AND_REINSTALL_L', 'Summit Exteriors', 'Remove and reinstall (L)', 'EA', 3000.0, ''],
  ['SUMMIT_REPAIR_10_CHIMNEY_FLASHING_M', 'Summit Exteriors', 'Repair 10 Chimney Flashing (M)', 'EA', 265.0, ''],
  ['SUMMIT_REPAIR_6_8_CHIMNEY_FLASHING_M', 'Summit Exteriors', 'Repair 6-8 Chimney Flashing (M)', 'EA', 125.0, ''],
  ['SUMMIT_REPAIR_ADDITIONAL_LABOR_L', 'Summit Exteriors', 'Repair Additional Labor (L)', 'EA', 40.0, ''],
  ['SUMMIT_REPAIR_B_VENT_FLASHING_M', 'Summit Exteriors', 'Repair B-Vent Flashing (M)', 'EA', 85.0, ''],
  ['SUMMIT_REPAIR_B_VENT_CAP_M', 'Summit Exteriors', 'Repair B-vent Cap (M)', 'EA', 35.0, ''],
  ['SUMMIT_REPAIR_BOX_VENTS_M', 'Summit Exteriors', 'Repair Box Vents (M)', 'EA', 17.0, ''],
  ['SUMMIT_REPAIR_CEDAR_SHAKE_M', 'Summit Exteriors', 'Repair Cedar Shake (M)', 'EA', 200.0, ''],
  ['SUMMIT_REPAIR_ICE_AND_WATER_UNDERLAYMENT_M', 'Summit Exteriors', 'Repair Ice and Water Underlayment (M)', 'EA', 76.0, ''],
  ['SUMMIT_REPAIR_LABOR_L', 'Summit Exteriors', 'Repair Labor (L)', 'EA', 1000.0, ''],
  ['SUMMIT_REPAIR_LIFT_RENTAL_M', 'Summit Exteriors', 'Repair Lift Rental (M)', 'EA', 350.0, ''],
  ['SUMMIT_REPAIR_MATERIAL_M', 'Summit Exteriors', 'Repair Material (M)', 'EA', 1500.0, ''],
  ['SUMMIT_REPAIR_METAL_1_5_SCREWS_14_M', 'Summit Exteriors', 'Repair Metal 1.5 Screws #14 (M)', 'EA', 36.0, ''],
  ['SUMMIT_REPAIR_METAL_1_5_SCREWS_17_M', 'Summit Exteriors', 'Repair Metal 1.5 Screws #17 (M)', 'EA', 57.0, ''],
  ['SUMMIT_REPAIR_METAL_2_5_SCREWS_14_M', 'Summit Exteriors', 'Repair Metal 2.5 Screws #14 (M)', 'EA', 49.0, ''],
  ['SUMMIT_REPAIR_METAL_CUSTOM_FLASHING_24GA_M', 'Summit Exteriors', 'Repair Metal Custom Flashing 24GA (M)', 'EA', 100.0, ''],
  ['SUMMIT_REPAIR_METAL_CUSTOM_FLASHING_26GA_M', 'Summit Exteriors', 'Repair Metal Custom Flashing 26GA (M)', 'EA', 60.0, ''],
  ['SUMMIT_REPAIR_METAL_HIP_AND_RIDGE_FLASHINGS_24GA_M', 'Summit Exteriors', 'Repair Metal Hip and Ridge Flashings 24GA (M)', 'EA', 44.0, ''],
  ['SUMMIT_REPAIR_METAL_HIP_AND_RIDGE_FLASHINGS_26GA_M', 'Summit Exteriors', 'Repair Metal Hip and Ridge Flashings 26GA (M)', 'EA', 34.0, ''],
  ['SUMMIT_REPAIR_METAL_PANEL_24_GA_M', 'Summit Exteriors', 'Repair Metal Panel 24 GA (M)', 'EA', 5.5, ''],
  ['SUMMIT_REPAIR_METAL_PANEL_26GA_M', 'Summit Exteriors', 'Repair Metal Panel 26GA (M)', 'EA', 4.5, ''],
  ['SUMMIT_REPAIR_METAL_PANEL_29GA_M', 'Summit Exteriors', 'Repair Metal Panel 29GA (M)', 'EA', 3.75, ''],
  ['SUMMIT_REPAIR_METAL_PERIMETER_FLASHING_26GA_M', 'Summit Exteriors', 'Repair Metal Perimeter Flashing 26GA (M)', 'EA', 39.0, ''],
  ['SUMMIT_REPAIR_METAL_PERIMETER_FLASHINGS_24GA_M', 'Summit Exteriors', 'Repair Metal Perimeter Flashings 24GA (M)', 'EA', 52.0, ''],
  ['SUMMIT_REPAIR_METAL_PIPE_BOOT_M', 'Summit Exteriors', 'Repair Metal Pipe Boot (M)', 'EA', 40.0, ''],
  ['SUMMIT_REPAIR_METAL_RIDGE_VENT_FOAM_CLOSURE_M', 'Summit Exteriors', 'Repair Metal Ridge Vent/Foam Closure (M)', 'EA', 37.3, ''],
  ['SUMMIT_REPAIR_METAL_VALLEY_FLASHING_24GA_M', 'Summit Exteriors', 'Repair Metal Valley Flashing 24GA (M)', 'EA', 61.0, ''],
  ['SUMMIT_REPAIR_METAL_VALLEY_FLASHING_26GA_M', 'Summit Exteriors', 'Repair Metal Valley Flashing 26GA (M)', 'EA', 43.0, ''],
  ['SUMMIT_REPAIR_METAL_WALL_FLASHING_24GA_M', 'Summit Exteriors', 'Repair Metal Wall Flashing 24GA (M)', 'EA', 39.0, ''],
  ['SUMMIT_REPAIR_METAL_WALL_FLASHINGS_26GA_M', 'Summit Exteriors', 'Repair Metal Wall Flashings 26GA (M)', 'EA', 24.0, ''],
  ['SUMMIT_REPAIR_MISC_SHOP_SUPPLIES_M', 'Summit Exteriors', 'Repair Misc/Shop Supplies (M)', 'EA', 25.0, ''],
  ['SUMMIT_REPAIR_PREMIUM_SHINGLE_HIP_AND_RIDGE_CAP_M', 'Summit Exteriors', 'Repair Premium Shingle Hip and Ridge Cap (M)', 'EA', 101.0, ''],
  ['SUMMIT_REPAIR_PREMIUM_SHINGLES_M', 'Summit Exteriors', 'Repair Premium Shingles (M)', 'EA', 60.0, ''],
  ['SUMMIT_REPAIR_ROOFING_NAILS_M', 'Summit Exteriors', 'Repair Roofing Nails (M)', 'EA', 34.0, ''],
  ['SUMMIT_REPAIR_S_5_SNOW_STOPS_M', 'Summit Exteriors', 'Repair S-5 Snow Stops (M)', 'EA', 62.0, ''],
  ['SUMMIT_REPAIR_SERVICE_TRUCK_L', 'Summit Exteriors', 'Repair Service Truck (L)', 'EA', 47.0, ''],
  ['SUMMIT_REPAIR_SERVICE_TRUCK_M', 'Summit Exteriors', 'Repair Service Truck (M)', 'EA', 15.0, ''],
  ['SUMMIT_REPAIR_SHEETING_M', 'Summit Exteriors', 'Repair Sheeting (M)', 'EA', 22.5, ''],
  ['SUMMIT_REPAIR_SHINGLE_PIPE_BOOT_M', 'Summit Exteriors', 'Repair Shingle Pipe Boot (M)', 'EA', 12.0, ''],
  ['SUMMIT_REPAIR_SHINGLE_RIDGE_VENT_M', 'Summit Exteriors', 'Repair Shingle Ridge Vent (M)', 'EA', 21.0, ''],
  ['SUMMIT_REPAIR_SHINGLE_STEP_FLASHING_M', 'Summit Exteriors', 'Repair Shingle Step Flashing (M)', 'EA', 2.4, ''],
  ['SUMMIT_REPAIR_SHINGLE_WALL_FLASHING_M', 'Summit Exteriors', 'Repair Shingle Wall Flashing (M)', 'EA', 14.0, ''],
  ['SUMMIT_REPAIR_SHINGLES_M', 'Summit Exteriors', 'Repair Shingles (M)', 'EA', 43.0, ''],
  ['SUMMIT_REPAIR_SKYLIGHT_FLASHING_KIT_M', 'Summit Exteriors', 'Repair Skylight Flashing Kit (M)', 'EA', 115.0, ''],
  ['SUMMIT_REPAIR_SNOW_STOPS_24GA_M', 'Summit Exteriors', 'Repair Snow Stops 24GA (M)', 'EA', 29.0, ''],
  ['SUMMIT_REPAIR_SPLIT_BOOTS_M', 'Summit Exteriors', 'Repair Split Boots (M)', 'EA', 45.0, ''],
  ['SUMMIT_REPAIR_STANDARD_SHINGLE_HIP_AND_RIDGE_CAP_M', 'Summit Exteriors', 'Repair Standard Shingle Hip and Ridge Cap (M)', 'EA', 96.0, ''],
  ['SUMMIT_REPAIR_STANDARD_SHINGLES_M', 'Summit Exteriors', 'Repair Standard Shingles (M)', 'EA', 45.0, ''],
  ['SUMMIT_REPAIR_SYNTHETIC_UNDERLAYMENT_M', 'Summit Exteriors', 'Repair Synthetic Underlayment (M)', 'EA', 76.0, ''],
  ['SUMMIT_RIGID_INSULATION_3_M', 'Summit Exteriors', 'Rigid Insulation 3 (M)', 'EA', 52.0, ''],
  ['SUMMIT_RIGID_INSULATION_R_30_MEASURED_BY_THE_SQFT_M', 'Summit Exteriors', 'Rigid Insulation R-30  Measured by the SQFT (M)', 'EA', 3.1, ''],
  ['SUMMIT_ROLLED_RIDGE_VENT_L', 'Summit Exteriors', 'Rolled Ridge Vent (L)', 'EA', 10.0, ''],
  ['SUMMIT_ROLLED_RIDGE_VENT_M', 'Summit Exteriors', 'Rolled Ridge Vent (M)', 'EA', 60.0, ''],
  ['SUMMIT_ROOF_ASSESMENT_M', 'Summit Exteriors', 'Roof Assesment (M)', 'EA', 150.0, ''],
  ['SUMMIT_S5_SNOW_STOPS_L', 'Summit Exteriors', 'S5 SNOW STOPS (L)', 'EA', 40.0, ''],
  ['SUMMIT_S5_SNOW_STOPS_M', 'Summit Exteriors', 'S5 SNOW STOPS (M)', 'EA', 115.0, ''],
  ['SUMMIT_SCUPPERS_M', 'Summit Exteriors', 'SCUPPERS (M)', 'EA', 150.0, ''],
  ['SUMMIT_SECOND_STORY_ALUMINUM_RAINCHAIN_L', 'Summit Exteriors', 'SECOND STORY ALUMINUM RAINCHAIN (L)', 'EA', 20.0, ''],
  ['SUMMIT_SECOND_STORY_ALUMINUM_RAINCHAIN_M', 'Summit Exteriors', 'SECOND STORY ALUMINUM RAINCHAIN (M)', 'EA', 220.0, ''],
  ['SUMMIT_SHINGLE_ROOFTOP_DELIVERY_M', 'Summit Exteriors', 'SHINGLE ROOFTOP DELIVERY (M)', 'EA', 75.0, ''],
  ['SUMMIT_SHINGLE_STEEP_PITCH_8_12_9_12_L', 'Summit Exteriors', 'SHINGLE STEEP PITCH 8/12-9/12 (L)', 'EA', 20.0, ''],
  ['SUMMIT_SHINGLES_STEEP_PITCH_10_12_11_12_L', 'Summit Exteriors', 'SHINGLES STEEP PITCH 10/12-11/12 (L)', 'EA', 30.0, ''],
  ['SUMMIT_SHINGLES_STEEP_PITCH_12_12_12_13_L', 'Summit Exteriors', 'SHINGLES STEEP PITCH 12/12-12/13 (L)', 'EA', 40.0, ''],
  ['SUMMIT_SHINGLES_STEEP_PITCH_14_12_12_15_L', 'Summit Exteriors', 'SHINGLES STEEP PITCH 14/12-12/15 (L)', 'EA', 50.0, ''],
  ['SUMMIT_SINGLE_STORY_ALUMINUM_RAINCHAIN_L', 'Summit Exteriors', 'SINGLE STORY ALUMINUM RAINCHAIN (L)', 'EA', 20.0, ''],
  ['SUMMIT_SINGLE_STORY_ALUMINUM_RAINCHAIN_M', 'Summit Exteriors', 'SINGLE STORY ALUMINUM RAINCHAIN (M)', 'EA', 140.0, ''],
  ['SUMMIT_SKYLIGHT_FLASHING_L', 'Summit Exteriors', 'SKYLIGHT FLASHING (L)', 'EA', 160.0, ''],
  ['SUMMIT_SKYLIGHT_FLASHING_M', 'Summit Exteriors', 'SKYLIGHT FLASHING (M)', 'EA', 115.0, ''],
  ['SUMMIT_SMALL_CHIMNEY_RE_FLASH_L', 'Summit Exteriors', 'SMALL CHIMNEY RE-FLASH (L)', 'EA', 180.0, ''],
  ['SUMMIT_SMALL_CHIMNEY_RE_FLASH_M', 'Summit Exteriors', 'SMALL CHIMNEY RE-FLASH (M)', 'EA', 45.0, ''],
  ['SUMMIT_SNAP_Z_STANDING_SEAM_RIDGE_VENT_26GA_M', 'Summit Exteriors', 'SNAP-Z STANDING SEAM RIDGE VENT 26GA (M)', 'EA', 4.69, ''],
  ['SUMMIT_SOLAR_ATTIC_FAN_M', 'Summit Exteriors', 'SOLAR ATTIC FAN (M)', 'EA', 563.0, ''],
  ['SUMMIT_SOLAR_TUBE_FLASHING_L', 'Summit Exteriors', 'SOLAR TUBE FLASHING (L)', 'EA', 80.0, ''],
  ['SUMMIT_SOLAR_TUBE_FLASHING_M', 'Summit Exteriors', 'SOLAR TUBE FLASHING (M)', 'EA', 50.0, ''],
  ['SUMMIT_STANDARD_SHINGLE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_L', 'Summit Exteriors', 'STANDARD SHINGLE TEAR OFF AND DISPOSAL (SINGLE LAYER) (L)', 'EA', 50.0, ''],
  ['SUMMIT_STANDARD_SHINGLE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_M', 'Summit Exteriors', 'STANDARD SHINGLE TEAR OFF AND DISPOSAL (SINGLE LAYER) (M)', 'EA', 8.0, ''],
  ['SUMMIT_STANDING_SEAM_EAVE_D_DRIP_EDGE_24GA_M', 'Summit Exteriors', 'STANDING SEAM EAVE (D DRIP EDGE) 24GA (M)', 'EA', 31.55, ''],
  ['SUMMIT_STANDING_SEAM_EAVE_D_DRIP_EDGE_26GA_M', 'Summit Exteriors', 'STANDING SEAM EAVE (D DRIP EDGE) 26GA (M)', 'EA', 23.12, ''],
  ['SUMMIT_STANDING_SEAM_ENDWALL_FLASHING_OPEN_HEM_24GA_L', 'Summit Exteriors', 'STANDING SEAM ENDWALL FLASHING OPEN HEM 24GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_STANDING_SEAM_ENDWALL_FLASHING_OPEN_HEM_24GA_M', 'Summit Exteriors', 'STANDING SEAM ENDWALL FLASHING OPEN HEM 24GA (M)', 'EA', 37.25, ''],
  ['SUMMIT_STANDING_SEAM_ENDWALL_FLASHING_OPEN_HEM_26GA_L', 'Summit Exteriors', 'STANDING SEAM ENDWALL FLASHING OPEN HEM 26GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_STANDING_SEAM_ENDWALL_FLASHING_OPEN_HEM_26GA_M', 'Summit Exteriors', 'STANDING SEAM ENDWALL FLASHING OPEN HEM 26GA (M)', 'EA', 26.87, ''],
  ['SUMMIT_STANDING_SEAM_PITCH_BREAK_TRANSITION_24GA_L', 'Summit Exteriors', 'STANDING SEAM PITCH BREAK TRANSITION 24GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_STANDING_SEAM_PITCH_BREAK_TRANSITION_24GA_M', 'Summit Exteriors', 'STANDING SEAM PITCH BREAK TRANSITION 24GA (M)', 'EA', 61.25, ''],
  ['SUMMIT_STANDING_SEAM_PITCH_BREAK_TRANSITION_26GA_L', 'Summit Exteriors', 'STANDING SEAM PITCH BREAK TRANSITION 26GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_STANDING_SEAM_PITCH_BREAK_TRANSITION_26GA_M', 'Summit Exteriors', 'STANDING SEAM PITCH BREAK TRANSITION 26GA (M)', 'EA', 44.21, ''],
  ['SUMMIT_STANDING_SEAM_SIDEWALL_FLASHING_OPEN_HEM_24GA_L', 'Summit Exteriors', 'STANDING SEAM SIDEWALL FLASHING OPEN HEM 24GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_STANDING_SEAM_SIDEWALL_FLASHING_OPEN_HEM_24GA_M', 'Summit Exteriors', 'STANDING SEAM SIDEWALL FLASHING OPEN HEM 24GA (M)', 'EA', 37.25, ''],
  ['SUMMIT_STANDING_SEAM_SIDEWALL_FLASHING_OPEN_HEM_26GA_L', 'Summit Exteriors', 'STANDING SEAM SIDEWALL FLASHING OPEN HEM 26GA (L)', 'EA', 50.0, ''],
  ['SUMMIT_STANDING_SEAM_SIDEWALL_FLASHING_OPEN_HEM_26GA_M', 'Summit Exteriors', 'STANDING SEAM SIDEWALL FLASHING OPEN HEM 26GA (M)', 'EA', 26.89, ''],
  ['SUMMIT_SYNTHETIC_UNDERLAYMENT_M', 'Summit Exteriors', 'SYNTHETIC UNDERLAYMENT (M)', 'EA', 78.44, ''],
  ['SUMMIT_SALVADORS_TPO_LABOR_AND_MATERIAL_M', 'Summit Exteriors', 'Salvadors TPO labor and material (M)', 'EA', 12711.16, ''],
  ['SUMMIT_SCAFFOLDING', 'Summit Exteriors', 'Scaffolding', 'EA', 15000.0, ''],
  ['SUMMIT_SEAMER_RENTAL_M', 'Summit Exteriors', 'Seamer Rental (M)', 'EA', 1000.0, ''],
  ['SUMMIT_SIDING_LABOR_DO_NOT_USE_L', 'Summit Exteriors', 'Siding Labor - Do not use (L)', 'EA', 79515.0, ''],
  ['SUMMIT_SIDING_TRIMS_24GA_M', 'Summit Exteriors', 'Siding Trims - 24GA (M)', 'EA', 2.0, ''],
  ['SUMMIT_SITE_SUPERVISOR_L', 'Summit Exteriors', 'Site Supervisor (L)', 'EA', 275.0, ''],
  ['SUMMIT_SKYLIGHT_2246_CURB_MOUNT_FIXED_M', 'Summit Exteriors', 'Skylight 2246 Curb Mount Fixed (M)', 'EA', 488.0, ''],
  ['SUMMIT_SKYLIGHT_4646_VELUX_SOLAR_M', 'Summit Exteriors', 'Skylight 4646 Velux Solar (M)', 'EA', 2081.0, ''],
  ['SUMMIT_SKYLIGHT_C06_DECK_MOUNT_FIXED_M', 'Summit Exteriors', 'Skylight C06 Deck Mount Fixed (M)', 'EA', 665.0, ''],
  ['SUMMIT_SNOW_RETENTION_M', 'Summit Exteriors', 'Snow Retention (M)', 'EA', 25.0, ''],
  ['SUMMIT_SOFFIT_L', 'Summit Exteriors', 'Soffit (L)', 'EA', 6.0, ''],
  ['SUMMIT_SOFFIT_M', 'Summit Exteriors', 'Soffit (M)', 'EA', 8.0, ''],
  ['SUMMIT_SOFFIT_LABOR_DO_NOT_USE_L', 'Summit Exteriors', 'Soffit Labor - Do not use (L)', 'EA', 9000.0, ''],
  ['SUMMIT_SOFFIT_VENT_M', 'Summit Exteriors', 'Soffit Vent (M)', 'EA', 8.0, ''],
  ['SUMMIT_SOLAR_ATTIC_VENT_L', 'Summit Exteriors', 'Solar Attic Vent (L)', 'EA', 20.0, ''],
  ['SUMMIT_SOLAR_ATTIC_VENT_M', 'Summit Exteriors', 'Solar Attic Vent (M)', 'EA', 140.0, ''],
  ['SUMMIT_SPECIAL_SHAINA_PANEL_ONE_TIME_USE_M', 'Summit Exteriors', 'Special Shaina Panel - One time use (M)', 'EA', 3.25, ''],
  ['SUMMIT_SPOKANE_PROJECT_60_MIL_TPO_M', 'Summit Exteriors', 'Spokane Project  60 Mil TPO (M)', 'EA', 6.46, ''],
  ['SUMMIT_SPOKANE_PROJECT_PARAPET_CAP_M', 'Summit Exteriors', 'Spokane Project Parapet Cap (M)', 'EA', 6.4, ''],
  ['SUMMIT_SPOKANE_PROJECT_TAPER_M', 'Summit Exteriors', 'Spokane Project Taper (M)', 'EA', 825.0, ''],
  ['SUMMIT_SQUARE_STEEL_DOWNSPOUT_L', 'Summit Exteriors', 'Square Steel Downspout (L)', 'EA', 75.0, ''],
  ['SUMMIT_SQUARE_STEEL_DOWNSPOUT_M', 'Summit Exteriors', 'Square Steel Downspout (M)', 'EA', 250.0, ''],
  ['SUMMIT_STANDARD_FINISH_METAL_SIDING_PACKAGE_L', 'Summit Exteriors', 'Standard Finish Metal Siding Package (L)', 'EA', 8500.0, ''],
  ['SUMMIT_STANDARD_FINISH_METAL_SIDING_PACKAGE_M', 'Summit Exteriors', 'Standard Finish Metal Siding Package (M)', 'EA', 8533.0, ''],
  ['SUMMIT_STEEL_FASCIA_DO_NOT_USE_L', 'Summit Exteriors', 'Steel Fascia (do not use) (L)', 'EA', 4.0, ''],
  ['SUMMIT_STRUCTURAL_SCREW_10_M', 'Summit Exteriors', 'Structural Screw - 10 (M)', 'EA', 1.25, ''],
  ['SUMMIT_SUN_TUNNEL_EXTENTIONS_L', 'Summit Exteriors', 'Sun Tunnel Extentions (L)', 'EA', 50.0, ''],
  ['SUMMIT_SUN_TUNNEL_EXTENTIONS_M', 'Summit Exteriors', 'Sun Tunnel Extentions (M)', 'EA', 200.0, ''],
  ['SUMMIT_T_PATCH_M', 'Summit Exteriors', 'T Patch (M)', 'EA', 1.06, ''],
  ['SUMMIT_T_PANELS_2_3_8_M', 'Summit Exteriors', 'T-Panels 2 3/8 (M)', 'EA', 4.0, ''],
  ['SUMMIT_TILE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_L', 'Summit Exteriors', 'TILE TEAR OFF AND DISPOSAL (SINGLE LAYER) (L)', 'EA', 175.0, ''],
  ['SUMMIT_TILE_TEAR_OFF_AND_DISPOSAL_SINGLE_LAYER_M', 'Summit Exteriors', 'TILE TEAR OFF AND DISPOSAL (SINGLE LAYER) (M)', 'EA', 10.0, ''],
  ['SUMMIT_TPO_80_MIL_UPGRADE_M', 'Summit Exteriors', 'TPO 80 Mil Upgrade (M)', 'EA', 770.0, ''],
  ['SUMMIT_TPO_ADHESIVE_M', 'Summit Exteriors', 'TPO Adhesive (M)', 'EA', 679.0, ''],
  ['SUMMIT_TPO_BOX_VENT_M', 'Summit Exteriors', 'TPO BOX VENT (M)', 'EA', 62.0, ''],
  ['SUMMIT_TPO_CLAD_EDGE_METAL_STANDARD_M', 'Summit Exteriors', 'TPO Clad Edge Metal - Standard (M)', 'EA', 43.5, ''],
  ['SUMMIT_TPO_LABOR_M', 'Summit Exteriors', 'TPO Labor (M)', 'EA', 120.0, ''],
  ['SUMMIT_TPO_ROOF_LABOR_L', 'Summit Exteriors', 'TPO Roof Labor (L)', 'EA', 80000.0, ''],
  ['SUMMIT_TPO_ROOF_LABOR_DYNAMIC_DENTAL', 'Summit Exteriors', 'TPO Roof Labor Dynamic Dental', 'EA', 20000.0, ''],
  ['SUMMIT_TPO_SECTION_L', 'Summit Exteriors', 'TPO Section (L)', 'EA', 2599.0, ''],
  ['SUMMIT_TPO_SECTION_M', 'Summit Exteriors', 'TPO Section (M)', 'EA', 2500.0, ''],
  ['SUMMIT_TPO_SINGLE_PLY_MEMBRANE_60_MIL_M', 'Summit Exteriors', 'TPO Single Ply Membrane 60 Mil (M)', 'EA', 853.33, ''],
  ['SUMMIT_TPO_SINGLE_PLY_MEMBRANE_60_MIL_4_X100_M', 'Summit Exteriors', 'TPO Single Ply Membrane 60 Mil 4\'x100\' (M)', 'EA', 298.0, ''],
  ['SUMMIT_TPO_WALKWAY_M', 'Summit Exteriors', 'TPO Walkway (M)', 'EA', 564.0, ''],
  ['SUMMIT_TRA_SYSTEM_BARRON_ONE_TIME_USE_L', 'Summit Exteriors', 'TRA System - Barron - One time use (L)', 'EA', 20252.0, ''],
  ['SUMMIT_TAPER_PACKAGE_ADJUST_PRICE_BASED_ON_PROJECT_M', 'Summit Exteriors', 'Taper Package - Adjust Price Based On Project (M)', 'EA', 3500.0, ''],
  ['SUMMIT_TAYLOR_METAL_CONTOUR_C_5_L', 'Summit Exteriors', 'Taylor Metal Contour C-5 (L)', 'EA', 6.0, ''],
  ['SUMMIT_TAYLOR_METAL_CONTOUR_C_5_M', 'Summit Exteriors', 'Taylor Metal Contour C-5 (M)', 'EA', 4.75, ''],
  ['SUMMIT_TERMINATION_BAR_M', 'Summit Exteriors', 'Termination Bar (M)', 'EA', 13.45, ''],
  ['SUMMIT_TITANIUM_PSU_30_M', 'Summit Exteriors', 'Titanium PSU-30 (M)', 'EA', 141.5, ''],
  ['SUMMIT_TITANIUM_UDL_30_M', 'Summit Exteriors', 'Titanium UDL-30 (M)', 'EA', 262.5, ''],
  ['SUMMIT_TRANSITIONS_TRIM_24_GA_M', 'Summit Exteriors', 'Transitions Trim 24 GA (M)', 'EA', 2.0, ''],
  ['SUMMIT_TRIMS', 'Summit Exteriors', 'Trims', 'EA', 1.5, ''],
  ['SUMMIT_TRIPLE_BAR_ALUMINUM_RAIL_SYSTEM_DO_NOT_USE_L', 'Summit Exteriors', 'Triple Bar Aluminum Rail System - Do not use (L)', 'EA', 12487.0, ''],
  ['SUMMIT_TRIPLE_BAR_ALUMINUM_RAIL_SYSTEM_DO_NOT_USE_M', 'Summit Exteriors', 'Triple Bar Aluminum Rail System - Do not use (M)', 'EA', 37630.0, ''],
  ['SUMMIT_UPGRADE_CERTAINTEED_PRESIDENTIAL_SHAKE_TL_M', 'Summit Exteriors', 'UPGRADE - CERTAINTEED PRESIDENTIAL SHAKE TL (M)', 'EA', 24.0, ''],
  ['SUMMIT_UPGRADE_5_ALUMINUM_SEAMLESS_GUTTERS_L', 'Summit Exteriors', 'UPGRADE 5 ALUMINUM SEAMLESS GUTTERS (L)', 'EA', 2.5, ''],
  ['SUMMIT_UPGRADE_5_ALUMINUM_SEAMLESS_GUTTERS_M', 'Summit Exteriors', 'UPGRADE 5 ALUMINUM SEAMLESS GUTTERS (M)', 'EA', 2.1, ''],
  ['SUMMIT_UPGRADE_5_ALUMINUM_SEAMLESS_GUTTERS_REMOVAL_L', 'Summit Exteriors', 'UPGRADE 5 ALUMINUM SEAMLESS GUTTERS + REMOVAL (L)', 'EA', 3.5, ''],
  ['SUMMIT_UPGRADE_5_ALUMINUM_SEAMLESS_GUTTERS_REMOVAL_M', 'Summit Exteriors', 'UPGRADE 5 ALUMINUM SEAMLESS GUTTERS + REMOVAL (M)', 'EA', 2.1, ''],
  ['SUMMIT_UPGRADE_6_ALUMINUM_SEAMLESS_GUTTERS_L', 'Summit Exteriors', 'UPGRADE 6 ALUMINUM SEAMLESS GUTTERS (L)', 'EA', 2.5, ''],
  ['SUMMIT_UPGRADE_6_ALUMINUM_SEAMLESS_GUTTERS_M', 'Summit Exteriors', 'UPGRADE 6 ALUMINUM SEAMLESS GUTTERS (M)', 'EA', 2.5, ''],
  ['SUMMIT_UPGRADE_6_ALUMINUM_SEAMLESS_GUTTERS_REMOVAL_L', 'Summit Exteriors', 'UPGRADE 6 ALUMINUM SEAMLESS GUTTERS + REMOVAL (L)', 'EA', 3.0, ''],
  ['SUMMIT_UPGRADE_6_ALUMINUM_SEAMLESS_GUTTERS_REMOVAL_M', 'Summit Exteriors', 'UPGRADE 6 ALUMINUM SEAMLESS GUTTERS + REMOVAL (M)', 'EA', 2.5, ''],
  ['SUMMIT_UPGRADE_STANDING_SEAM_METAL_ACCENT_M', 'Summit Exteriors', 'UPGRADE STANDING SEAM METAL ACCENT (M)', 'EA', 800.0, ''],
  ['SUMMIT_UPGRADE_WOODMORE_SHAKE_SHINGLE_M', 'Summit Exteriors', 'UPGRADE WOODMORE SHAKE SHINGLE (M)', 'EA', 33.69, ''],
  ['SUMMIT_UPGRADE_TO_BRAVA_SOLID_SLATE_ACCESSORIES_FOR_THE_VALLEY_M', 'Summit Exteriors', 'UPGRADE to Brava Solid Slate accessories for the valley (M)', 'EA', 7092.0, ''],
  ['SUMMIT_UNIVERSAL_CORNER_TPO_M', 'Summit Exteriors', 'Universal Corner - TPO (M)', 'EA', 0.8, ''],
  ['SUMMIT_VAPOR_BARRIER_TPO_M', 'Summit Exteriors', 'Vapor Barrier - TPO (M)', 'EA', 462.35, ''],
  ['SUMMIT_VELUX_2246_SKYLIGHT_M', 'Summit Exteriors', 'Velux 2246 Skylight (M)', 'EA', 488.0, ''],
  ['SUMMIT_VELUX_4672_SKYLIGHT_M', 'Summit Exteriors', 'Velux 4672 Skylight (M)', 'EA', 988.0, ''],
  ['SUMMIT_VELUX_C06_SKYLIGHT_M', 'Summit Exteriors', 'Velux C06 Skylight (M)', 'EA', 665.0, ''],
  ['SUMMIT_VELUX_D06_SKYLIGHT_L', 'Summit Exteriors', 'Velux D06 Skylight (L)', 'EA', 100.0, ''],
  ['SUMMIT_VELUX_D06_SKYLIGHT_M', 'Summit Exteriors', 'Velux D06 Skylight (M)', 'EA', 677.0, ''],
  ['SUMMIT_VELUX_FCM_1430_CURBMOUNT_SKYLIGHT_L', 'Summit Exteriors', 'Velux FCM 1430 Curbmount Skylight (L)', 'EA', 100.0, ''],
  ['SUMMIT_VELUX_FCM_1430_CURBMOUNT_SKYLIGHT_M', 'Summit Exteriors', 'Velux FCM 1430 Curbmount Skylight (M)', 'EA', 290.0, ''],
  ['SUMMIT_VELUX_FS_M08_2004D_22BG06A_M', 'Summit Exteriors', 'Velux FS M08 2004D 22BG06A (M)', 'EA', 1200.0, ''],
  ['SUMMIT_VELUX_M08_M', 'Summit Exteriors', 'Velux M08 (M)', 'EA', 1129.0, ''],
  ['SUMMIT_VELUX_S06_L', 'Summit Exteriors', 'Velux S06 (L)', 'EA', 150.0, ''],
  ['SUMMIT_VELUX_S06_M', 'Summit Exteriors', 'Velux S06 (M)', 'EA', 1246.0, ''],
  ['SUMMIT_VELUX_VCM_2234_SKYLIGHT_M', 'Summit Exteriors', 'Velux VCM 2234 Skylight (M)', 'EA', 1765.0, ''],
  ['SUMMIT_VELUX_VCM_3046_SKYLIGHT_M', 'Summit Exteriors', 'Velux VCM 3046 Skylight (M)', 'EA', 1403.0, ''],
  ['SUMMIT_VELUX_VS_MANUAL_FRESH_AIR_M', 'Summit Exteriors', 'Velux VS Manual Fresh Air (M)', 'EA', 970.0, ''],
  ['SUMMIT_VENT_BOOT_1_6_TPO_M', 'Summit Exteriors', 'Vent Boot 1-6 TPO (M)', 'EA', 7.33, ''],
  ['SUMMIT_VERTICAL_SIDING_26GA_L', 'Summit Exteriors', 'Vertical Siding 26GA (L)', 'EA', 6.0, ''],
  ['SUMMIT_VERTICAL_SIDING_26GA_M', 'Summit Exteriors', 'Vertical Siding 26GA (M)', 'EA', 6.0, ''],
  ['SUMMIT_VESTA_PLANKS_L', 'Summit Exteriors', 'Vesta Planks (L)', 'EA', 9.0, ''],
  ['SUMMIT_VESTA_PLANKS_M', 'Summit Exteriors', 'Vesta Planks (M)', 'EA', 10.05, ''],
  ['SUMMIT_VEVOR_5_GUTTER_GUARDS_L', 'Summit Exteriors', 'Vevor 5 Gutter Guards (L)', 'EA', 3.0, ''],
  ['SUMMIT_VEVOR_5_GUTTER_GUARDS_M', 'Summit Exteriors', 'Vevor 5 Gutter Guards (M)', 'EA', 66.0, ''],
  ['SUMMIT_WALL_FLASHING_M', 'Summit Exteriors', 'WALL FLASHING (M)', 'EA', 13.0, ''],
  ['SUMMIT_WHIRLYBIRD_VENT_M', 'Summit Exteriors', 'WHIRLYBIRD VENT (M)', 'EA', 64.0, ''],
  ['SUMMIT_WARRANTY_DO_NOT_USE_M', 'Summit Exteriors', 'Warranty - Do Not Use (M)', 'EA', 4210.0, ''],
  ['SUMMIT_WARRANTY_CALGARY_COURT', 'Summit Exteriors', 'Warranty Calgary Court', 'EA', 3510.0, ''],
  ['SUMMIT_WATER_CUT_OFF_MASTIC_M', 'Summit Exteriors', 'Water Cut-off Mastic (M)', 'EA', 10.16, ''],
  ['SUMMIT_WESTERN_STATES_METAL_PACKAGE_DO_NOT_USE_M', 'Summit Exteriors', 'Western States Metal Package - Do not use (M)', 'EA', 37975.73, ''],
  ['SUMMIT_WESTERN_STATES_METAL_SIDING_DO_NOT_USE_M', 'Summit Exteriors', 'Western States Metal Siding - Do not use (M)', 'EA', 8.55, ''],
  ['SUMMIT_WOODGRAIN_UPGRADE_26GA_M', 'Summit Exteriors', 'Woodgrain Upgrade 26GA (M)', 'EA', 1.0, ''],
  ['SUMMIT_Z_TRIM_M', 'Summit Exteriors', 'Z TRIM (M)', 'EA', 14.2, ''],
  ['SUMMIT_ZINC_STRIP_L', 'Summit Exteriors', 'ZINC STRIP (L)', 'EA', 100.0, ''],
  ['SUMMIT_ZINC_STRIP_M', 'Summit Exteriors', 'ZINC STRIP (M)', 'EA', 50.0, ''],
  ['SUMMIT_ZIP_R_1_L', 'Summit Exteriors', 'Zip R 1 (L)', 'EA', 25.0, ''],
  ['SUMMIT_ZIP_R_1_M', 'Summit Exteriors', 'Zip R 1 (M)', 'EA', 69.0, ''],
  ['SUMMIT_ZIP_SEALING_TAPE_M', 'Summit Exteriors', 'Zip Sealing Tape (M)', 'EA', 38.0, ''],
  ['SUMMIT_BALLAST_PEA_GRAVEL_M', 'Summit Exteriors', 'ballast - Pea Gravel (M)', 'EA', 3000.0, ''],
  ['SUMMIT_BRAVA_PACKAGE_L', 'Summit Exteriors', 'brava package (L)', 'EA', 25000.0, ''],
  ['SUMMIT_BRAVA_PACKAGE_M', 'Summit Exteriors', 'brava package (M)', 'EA', 81973.0, ''],
  ['SUMMIT_CUSTOM_CAP_M', 'Summit Exteriors', 'custom cap (M)', 'EA', 1500.0, ''],
  ['SUMMIT_SHINGLE_TEST_L', 'Summit Exteriors', 'shingle test (L)', 'EA', 60.0, ''],
  ['SUMMIT_SHINGLE_TEST_M', 'Summit Exteriors', 'shingle test (M)', 'EA', 120.0, ''],
];
